-- Original WordLoop editorial expansion, exp1: 25 new senses per level.
-- Append-only content; no scraped dictionary or course text.
-- Permanent exp1 UUID namespace + level/sequence; never regenerate IDs after releveling.
with cards(level,seq,term,pos,domain,topic,meaning,example) as (values
('L1',1,'apple','noun','general','food','사과','I put an apple in my lunch bag.'),
('L1',2,'rice','noun','general','food','쌀; 밥','We eat rice with vegetables.'),
('L1',3,'cup','noun','general','home','컵','Your cup is on the kitchen table.'),
('L1',4,'bed','noun','general','home','침대','The cat is sleeping under my bed.'),
('L1',5,'window','noun','general','home','창문','I can see a tree through the window.'),
('L1',6,'bag','noun','general','travel','가방','My bag is too big for this shelf.'),
('L1',7,'shoe','noun','general','clothing','신발 한 짝','There is a stone in my shoe.'),
('L1',8,'bus','noun','general','travel','버스','This bus goes to the beach.'),
('L1',9,'mother','noun','general','people','어머니','My mother makes soup on Sundays.'),
('L1',10,'child','noun','general','people','아이','The child is drawing a yellow sun.'),
('L1',11,'teacher','noun','academic','education','선생님','Our teacher knows all our names.'),
('L1',12,'pen','noun','academic','education','펜','Use a blue pen to write the date.'),
('L1',13,'shop','noun','workplace','shopping','가게','The shop sells fruit and bread.'),
('L1',14,'eat','verb','general','food','먹다','We eat lunch in the garden.'),
('L1',15,'drink','verb','general','food','마시다','I drink warm milk before bed.'),
('L1',16,'sleep','verb','general','habits','잠을 자다','The baby will sleep after lunch.'),
('L1',17,'sit','verb','academic','education','앉다','Please sit next to your partner.'),
('L1',18,'stand','verb','general','movement','서다','We stand near the door on the train.'),
('L1',19,'close','verb','workplace','office','닫다','Please close the box after you use it.'),
('L1',20,'wash','verb','general','home','씻다','Wash your hands before dinner.'),
('L1',21,'big','adjective','general','description','큰','We need a big table for six people.'),
('L1',22,'cold','adjective','general','weather','차가운; 추운','The water is cold this morning.'),
('L1',23,'hot','adjective','general','food','뜨거운','Be careful with the hot soup.'),
('L1',24,'slowly','adverb','general','movement','천천히','Walk slowly on the wet floor.'),
('L1',25,'under','preposition','general','location','~ 아래에','The ball is under the chair.'),

('L2',1,'lend','verb','general','people','빌려주다','Could you lend me an umbrella for the afternoon?'),
('L2',2,'repair','verb','workplace','service','수리하다','The mechanic can repair my bicycle today.'),
('L2',3,'prepare','verb','academic','education','준비하다','We prepare a short talk for each lesson.'),
('L2',4,'check','verb','workplace','operations','확인하다; 점검하다','Please check the address before sending the package.'),
('L2',5,'wait','verb','general','travel','기다리다','We can wait inside until the rain stops.'),
('L2',6,'join','verb','general','community','참여하다; 함께하다','Would you like to join our walking group?'),
('L2',7,'describe','verb','academic','communication','묘사하다; 특징을 말하다','Describe the animal without saying its name.'),
('L2',8,'need','verb','general','home','필요하다','You need a larger pot for this plant.'),
('L2',9,'prefer','verb','general','decisions','더 좋아하다','I prefer the quiet room at the back.'),
('L2',10,'happen','verb','general','events','일어나다; 발생하다','What will happen if we miss the last bus?'),
('L2',11,'neighbor','noun','general','people','이웃','Our neighbor waters the plants when we travel.'),
('L2',12,'appointment','noun','workplace','service','방문이나 상담 등을 위한 약속','I have an appointment at the hair salon at two.'),
('L2',13,'receipt','noun','workplace','shopping','영수증','The cashier put the receipt in the bag.'),
('L2',14,'entrance','noun','general','location','입구','The museum entrance is beside the fountain.'),
('L2',15,'luggage','noun','general','travel','여행 짐','We left our luggage at the hotel.'),
('L2',16,'hobby','noun','general','leisure','취미','Growing herbs is my favorite hobby.'),
('L2',17,'subject','noun','academic','education','학교에서 배우는 과목','History is the subject I enjoy most.'),
('L2',18,'address','noun','general','location','주소','Write your address on the back of the envelope.'),
('L2',19,'crowded','adjective','general','travel','사람들로 붐비는','The beach gets crowded on sunny weekends.'),
('L2',20,'polite','adjective','workplace','service','예의 바른','The receptionist was polite to every guest.'),
('L2',21,'ready','adjective','general','planning','준비가 된','Your lunch is ready in the kitchen.'),
('L2',22,'cheap','adjective','general','shopping','가격이 싼','This market is a good place to find cheap fruit.'),
('L2',23,'carefully','adverb','academic','education','주의 깊게','Read the question carefully before you answer.'),
('L2',24,'sometimes','adverb','general','habits','가끔','We sometimes take a different route home.'),
('L2',25,'until','preposition','workplace','time','~까지 계속','The front desk is open until midnight.'),

('L3',1,'achieve','verb','academic','education','노력하여 이루다','Setting small goals helped her achieve steady progress.'),
('L3',2,'consider','verb','general','decisions','고려하다','Consider the travel time before choosing a course.'),
('L3',3,'develop','verb','academic','education','발전시키다; 키우다','Group projects help students develop communication skills.'),
('L3',4,'encourage','verb','general','people','격려하다','My friends encourage me to keep practicing the guitar.'),
('L3',5,'offer','verb','workplace','service','제공하겠다고 제안하다','The hotel may offer us a different room.'),
('L3',6,'organize','verb','workplace','planning','조직하다; 준비하여 마련하다','Two volunteers will organize the weekend workshop.'),
('L3',7,'prevent','verb','general','health','막다; 예방하다','A secure lid helps prevent spills during travel.'),
('L3',8,'replace','verb','workplace','operations','교체하다','We need to replace the broken printer.'),
('L3',9,'solve','verb','academic','reasoning','해결하다','Drawing a picture helped us solve the problem.'),
('L3',10,'recommend','verb','general','communication','추천하다','Can you recommend a quiet place to study?'),
('L3',11,'complaint','noun','workplace','service','불만을 제기하는 말이나 글','The manager responded to my complaint about the delivery.'),
('L3',12,'advantage','noun','general','decisions','유리한 점; 장점','One advantage of living here is the short walk to work.'),
('L3',13,'behavior','noun','academic','education','행동; 행동 방식','The teacher noticed a change in classroom behavior.'),
('L3',14,'choice','noun','general','decisions','선택','Taking the earlier train was a good choice.'),
('L3',15,'condition','noun','workplace','operations','상태','The returned equipment is still in good condition.'),
('L3',16,'effort','noun','academic','education','노력','Learning to read music takes time and effort.'),
('L3',17,'permission','noun','workplace','policy','허락','You need permission to use the company van.'),
('L3',18,'progress','noun','academic','education','진전; 발전','The tutor checks our progress at the end of each month.'),
('L3',19,'suitable','adjective','general','decisions','적합한','This flat path is suitable for young children.'),
('L3',20,'necessary','adjective','workplace','operations','필요한','A second visit is necessary to finish the repairs.'),
('L3',21,'confident','adjective','general','feelings','자신감 있는','She feels more confident when speaking to new people.'),
('L3',22,'patient','adjective','general','people','참을성 있는','Our guide was patient while we practiced the new words.'),
('L3',23,'recently','adverb','general','time','최근에','A bakery recently opened across from the station.'),
('L3',24,'unless','conjunction','workplace','planning','~하지 않는 한','We will use the small room unless more guests arrive.'),
('L3',25,'in advance','phrase','general','planning','미리','Buy your train ticket in advance to save time.'),

('L4',1,'coordinate','verb','workplace','planning','여러 활동을 조율하다','One person will coordinate deliveries from the three suppliers.'),
('L4',2,'estimate','verb','workplace','planning','추산하다','The builder will estimate the cost after inspecting the roof.'),
('L4',3,'expand','verb','workplace','business','확장하다','The store plans to expand its delivery area next spring.'),
('L4',4,'resolve','verb','workplace','communication','문제나 갈등을 해결하다','A short call helped resolve the confusion about the order.'),
('L4',5,'respond','verb','general','communication','응답하다; 반응하다','How did the audience respond to the new ending?'),
('L4',6,'obtain','verb','academic','research','얻다; 입수하다','Students can obtain copies of the records from the archive.'),
('L4',7,'participate','verb','general','community','참가하다','Residents can participate in the garden project on Saturdays.'),
('L4',8,'prioritize','verb','workplace','planning','우선순위를 정하다','We should prioritize urgent repairs before repainting the office.'),
('L4',9,'proposal','noun','workplace','planning','제안; 제안서','The proposal includes a budget and a training schedule.'),
('L4',10,'procedure','noun','workplace','operations','정해진 절차','Follow the same procedure when checking each delivery.'),
('L4',11,'capacity','noun','workplace','operations','최대 수용량; 처리 능력','The warehouse is operating at full capacity this month.'),
('L4',12,'demand','noun','workplace','business','수요','Demand for bicycle repairs rises in early summer.'),
('L4',13,'objective','noun','academic','education','달성하려는 목표','The main objective of the lesson is to compare viewpoints.'),
('L4',14,'trend','noun','academic','research','변화의 추세','The chart shows a trend toward smaller households.'),
('L4',15,'survey','noun','academic','research','설문 조사','Our survey asks residents how they use the park.'),
('L4',16,'accurate','adjective','academic','research','정확한','Accurate measurements are essential for comparing the samples.'),
('L4',17,'appropriate','adjective','general','communication','상황에 적절한','Choose a greeting that is appropriate for the occasion.'),
('L4',18,'aware','adjective','general','community','알고 있는; 인식하는','Many residents are aware of the changes to the bus route.'),
('L4',19,'temporary','adjective','workplace','employment','임시의','She accepted a temporary position at the visitor center.'),
('L4',20,'potential','adjective','general','environment','잠재적인','The team discussed the potential effects on nearby streams.'),
('L4',21,'initially','adverb','academic','research','처음에는','Initially, the two groups produced similar results.'),
('L4',22,'in contrast','phrase','academic','reasoning','그와 대조적으로','The north side is shaded; in contrast, the south side receives sunlight all day.'),
('L4',23,'regarding','preposition','workplace','communication','~에 관하여','Please contact the office regarding changes to your booking.'),
('L4',24,'specify','verb','workplace','communication','구체적으로 명시하다','The order form must specify the size and color.'),
('L4',25,'adjust','verb','general','change','조정하다','You can adjust the seat height with this lever.'),

('L5',1,'implement','verb','workplace','operations','계획이나 제도를 실행하다','The library will implement the new booking system in stages.'),
('L5',2,'anticipate','verb','workplace','planning','미리 예상하다','We anticipate a rise in demand once the bridge opens.'),
('L5',3,'clarify','verb','academic','communication','명확하게 하다','A concrete example would clarify the difference between the two concepts.'),
('L5',4,'integrate','verb','academic','education','통합하다','The course will integrate fieldwork with classroom discussion.'),
('L5',5,'reinforce','verb','general','communication','강화하다','Regular updates reinforce public confidence in the project.'),
('L5',6,'revise','verb','academic','communication','수정하다; 개정하다','Revise the introduction so that it states your argument clearly.'),
('L5',7,'acknowledge','verb','general','communication','인정하다','We should acknowledge the limits of what this survey can tell us.'),
('L5',8,'exceed','verb','workplace','business','넘어서다; 초과하다','Repair costs may exceed the value of the old machine.'),
('L5',9,'criterion','noun','academic','reasoning','판단 기준','Accessibility is one criterion for selecting the venue.'),
('L5',10,'outcome','noun','academic','research','최종 결과','The study measured the outcome six months after training ended.'),
('L5',11,'scope','noun','workplace','planning','다루는 범위','The contract defines the scope of the maintenance work.'),
('L5',12,'priority','noun','general','community','우선적으로 중요한 일','Making the crossing safer is a priority for local parents.'),
('L5',13,'obligation','noun','workplace','policy','지켜야 할 의무','The agreement creates an obligation to report delays promptly.'),
('L5',14,'validity','noun','academic','research','타당성','The missing responses raise questions about the validity of the comparison.'),
('L5',15,'diverse','adjective','general','society','다양한','The program brings together people with diverse backgrounds.'),
('L5',16,'precise','adjective','academic','communication','정밀하고 명확한','Use precise language when describing how the samples were selected.'),
('L5',17,'comprehensive','adjective','academic','research','포괄적인','The report offers a comprehensive account of changes along the coast.'),
('L5',18,'reluctant','adjective','general','feelings','꺼리는; 내키지 않는','Residents were reluctant to support a plan with no published budget.'),
('L5',19,'inevitable','adjective','general','change','피할 수 없는','Some disruption is inevitable while the station is being rebuilt.'),
('L5',20,'ultimately','adverb','general','reasoning','궁극적으로; 결국','Ultimately, the decision depends on how much space we need.'),
('L5',21,'in conjunction with','phrase','workplace','organization','~와 함께; ~와 연계하여','The workshop will run in conjunction with the annual staff conference.'),
('L5',22,'compensate','verb','workplace','employment','보상하다','The company will compensate employees for the additional travel costs.'),
('L5',23,'undergo','verb','workplace','operations','과정이나 변화를 거치다','Every new device must undergo a series of safety checks.'),
('L5',24,'distribute','verb','general','community','나누어 주다; 배포하다','Volunteers distribute translated notices to households in the area.'),
('L5',25,'whereby','adverb','academic','reasoning','그것을 통해; 그렇게 함으로써','The paper describes a process whereby students review one another''s drafts.'),

('L6',1,'articulate','verb','academic','communication','생각을 명료하게 표현하다','The introduction should articulate the question that motivates the research.'),
('L6',2,'consolidate','verb','workplace','operations','여러 부분을 하나로 통합하다','The team will consolidate the regional reports into a single overview.'),
('L6',3,'devise','verb','academic','research','고안하다','Researchers must devise a method that works without expensive equipment.'),
('L6',4,'differentiate','verb','academic','reasoning','차이를 식별하여 구분하다','The analysis must differentiate temporary changes from lasting trends.'),
('L6',5,'endorse','verb','workplace','governance','공개적으로 지지하다','The committee declined to endorse the proposal without further consultation.'),
('L6',6,'entail','verb','workplace','planning','필연적으로 수반하다','Moving the archive would entail months of careful preparation.'),
('L6',7,'foster','verb','general','community','발달이나 성장을 촉진하다','Shared public spaces can foster a sense of belonging.'),
('L6',8,'overlook','verb','academic','research','중요한 것을 간과하다','A focus on averages can overlook differences between neighborhoods.'),
('L6',9,'premise','noun','academic','reasoning','논의의 바탕이 되는 전제','The argument depends on the premise that all participants had equal access.'),
('L6',10,'resilience','noun','general','society','어려움에서 회복하는 능력','The study explores how social ties contribute to community resilience.'),
('L6',11,'transparency','noun','workplace','governance','의사 결정이나 운영의 투명성','Publishing the selection criteria would improve transparency.'),
('L6',12,'viability','noun','workplace','planning','계속 운영하거나 실현할 수 있는 가능성','The trial will test the viability of a year-round ferry service.'),
('L6',13,'bias','noun','academic','research','판단이나 결과를 치우치게 하는 편향','Recruiting only online participants may introduce bias into the survey.'),
('L6',14,'cohesion','noun','general','society','집단의 결속력','The closure of shared meeting places weakened neighborhood cohesion.'),
('L6',15,'autonomy','noun','workplace','employment','스스로 결정할 수 있는 자율성','The new structure gives regional teams greater autonomy over scheduling.'),
('L6',16,'explicit','adjective','workplace','policy','분명하게 명시된','The policy needs an explicit statement about who can approve exceptions.'),
('L6',17,'implicit','adjective','academic','reasoning','직접 말하지 않아도 내포된','The argument contains an implicit assumption about equal starting conditions.'),
('L6',18,'tentative','adjective','academic','research','아직 확정되지 않은; 잠정적인','These conclusions remain tentative until the second survey is complete.'),
('L6',19,'compelling','adjective','academic','reasoning','강한 설득력이 있는','The repeated pattern provides a compelling reason to investigate further.'),
('L6',20,'marginal','adjective','workplace','business','차이나 효과가 아주 작은','The newer machine offers only a marginal improvement in output.'),
('L6',21,'irrespective of','phrase','general','society','~와 관계없이','The center welcomes residents irrespective of their employment status.'),
('L6',22,'predominantly','adverb','academic','research','주로; 대부분','The sample consists predominantly of people who commute by train.'),
('L6',23,'constrain','verb','workplace','planning','범위나 가능성을 제한하다','Limited storage space will constrain the range of products we can stock.'),
('L6',24,'elaborate','verb','academic','communication','자세히 설명하다','The speaker was asked to elaborate on how the categories were chosen.'),
('L6',25,'contradict','verb','academic','reasoning','주장이나 증거와 모순되다','The later interviews contradict the claim that all residents supported the plan.'),

('L7',1,'adjudicate','verb','workplace','governance','분쟁을 심사하여 판정하다','An independent panel will adjudicate disputes over the selection process.'),
('L7',2,'ameliorate','verb','general','society','불리한 상황을 개선하다','The grant is intended to ameliorate the effects of prolonged unemployment.'),
('L7',3,'attenuate','verb','academic','research','효과나 강도를 약화시키다','The protective coating may attenuate the effect of moisture on the sensor.'),
('L7',4,'obviate','verb','workplace','operations','필요성을 없애다','A shared booking calendar would obviate the need for separate confirmation calls.'),
('L7',5,'reify','verb','academic','reasoning','추상적 개념을 실체처럼 다루다','The critique warns that fixed labels can reify categories that change over time.'),
('L7',6,'eschew','verb','academic','communication','의도적으로 피하다','The author chose to eschew technical jargon in the public report.'),
('L7',7,'explicate','verb','academic','communication','의미나 논리를 상세히 풀어 설명하다','The final section will explicate the assumptions underlying the model.'),
('L7',8,'vitiate','verb','academic','reasoning','타당성이나 효력을 훼손하다','A systematic error in the measurements would vitiate the central conclusion.'),
('L7',9,'engender','verb','general','society','감정이나 상황을 발생시키다','Unexplained exceptions can engender distrust among participants.'),
('L7',10,'impugn','verb','general','communication','진실성이나 정당성에 의문을 제기하다','Critics sought to impugn the credibility of the report by questioning its funding.'),
('L7',11,'corollary','noun','academic','reasoning','앞선 명제에서 따라 나오는 결론','A corollary of this argument is that access alone does not ensure participation.'),
('L7',12,'exigency','noun','workplace','planning','긴급한 필요나 사정','The reserve can cover an operational exigency such as an unexpected relocation.'),
('L7',13,'equanimity','noun','general','feelings','어려움 속에서도 흔들리지 않는 침착함','She received the disappointing news with remarkable equanimity.'),
('L7',14,'intransigence','noun','workplace','communication','타협을 완강히 거부하는 태도','Negotiations stalled because of the intransigence of both delegations.'),
('L7',15,'salience','noun','academic','research','주의를 끄는 두드러짐','The experiment tests whether color increases the salience of a warning.'),
('L7',16,'veracity','noun','academic','research','내용의 진실성','Researchers checked the veracity of the account against contemporary records.'),
('L7',17,'contingent','adjective','workplace','planning','특정 조건에 달려 있는','The extension is contingent on securing access to the adjacent site.'),
('L7',18,'inimical','adjective','general','society','해를 끼치거나 적대적인','Constant surveillance can create conditions inimical to open discussion.'),
('L7',19,'specious','adjective','academic','reasoning','겉보기에는 그럴듯하지만 잘못된','The claim rests on a specious comparison between unrelated groups.'),
('L7',20,'unequivocal','adjective','workplace','communication','모호함 없이 명백한','The board issued an unequivocal rejection of the proposed closure.'),
('L7',21,'provisional','adjective','academic','research','추후 검토를 전제로 한 잠정적인','The classification is provisional pending examination of the remaining samples.'),
('L7',22,'commensurate','adjective','workplace','employment','정도나 규모에 상응하는','The role should carry authority commensurate with its responsibilities.'),
('L7',23,'insofar as','conjunction','academic','reasoning','~하는 범위에서; ~하는 한','The model is useful insofar as it explains variation across the observed cases.'),
('L7',24,'ostensibly','adverb','workplace','governance','표면상으로는','The review was ostensibly independent, though the sponsor selected every panel member.'),
('L7',25,'enjoin','verb','workplace','governance','공식적으로 명하거나 요구하다','The code of conduct enjoins all reviewers to disclose competing interests.')
)
insert into public.vocabulary_catalog(id,content_key,term,meaning,example,part_of_speech,difficulty,cefr_anchor,cefr_band,topics,domains,skills,priority,source,license,provenance)
select ('e1000000-0000-4000-8000-' || lpad(l.ordinal::text,2,'0') || lpad(c.seq::text,10,'0'))::uuid,
  'wl-exp1-' || lower(c.level) || '-' || lpad(c.seq::text,3,'0'),
  c.term,c.meaning,c.example,c.pos,c.level,l.cefr_anchor,l.cefr_band,
  array[c.topic],array[c.domain],
  case c.domain when 'workplace' then array['comprehension','conversation','toeic_listening','toeic_reading']
    when 'academic' then array['literacy','production','comprehension']
    else array['literacy','production','comprehension','conversation'] end,
  70,'WordLoop original editorial content','LicenseRef-WordLoop-Original',
  jsonb_build_object('method','original WordLoop AI-assisted editorial content; no imported course or dictionary text',
    'version','exp1','level_basis','editorial estimate, not certified CEFR classification',
    'review_status','initial editorial pass; not independently calibrated',
    'rights','Original project content; no third-party redistribution license asserted')
from cards c join public.difficulty_levels l on l.code = c.level;

-- Same transparent editorial rules as v1, scoped only to exp1 cards and existing tracks.
with classified as (
  select c.id catalog_id,t.id track_id,
    case
      when t.code = 'det_120_plus' and c.difficulty = 'L5' then 'core'
      when t.code = 'det_120_plus' and c.difficulty = 'L6' then 'stretch'
      when t.code = 'toeic_750' and c.difficulty in ('L3','L4') then 'core'
      when t.code = 'toeic_750' and c.difficulty = 'L5' then 'stretch'
      when t.code = 'toeic_900' and c.difficulty in ('L4','L5') then 'core'
      when t.code = 'toeic_900' and c.difficulty = 'L6' then 'stretch'
      else 'optional' end role,
    case when t.exam = 'DET' then not ('workplace' = any(c.domains))
      else 'workplace' = any(c.domains) end domain_match
  from public.vocabulary_catalog c cross join public.learning_tracks t
  where c.content_key like 'wl-exp1-%' and t.code in ('det_120_plus','toeic_750','toeic_900')
)
insert into public.catalog_track_rules(catalog_id,track_id,role,priority,weight,rationale)
select catalog_id,track_id,role,
  (case role when 'core' then 80 when 'stretch' then 50 else 10 end) + case when domain_match then 10 else 0 end,
  (case role when 'core' then 1.0 when 'stretch' then 0.35 else 0.1 end) * case when domain_match then 1.2 else 1.0 end,
  'Editorial level rule; domain affinity adds priority. Optional means fallback, not automatic promotion.'
from classified;
