-- Original WordLoop editorial expansion, exp2: 50 new cards per level.
-- Append-only content; no scraped dictionary or proprietary course text.
-- Permanent exp2 UUID namespace + level/sequence; never regenerate IDs after releveling.
with cards(level,seq,term,pos,domain,topic,meaning,example) as (values
('L1',1,'chair','noun','general','home','의자','Please put the chair by the table.'),
('L1',2,'table','noun','general','home','식탁; 테이블','The keys are on the table.'),
('L1',3,'phone','noun','general','communication','휴대전화','My phone is in my coat pocket.'),
('L1',4,'clock','noun','general','time','시계','The clock says it is eight.'),
('L1',5,'key','noun','general','home','열쇠','I keep the key in my bag.'),
('L1',6,'light','noun','general','home','불빛; 조명','Turn on the light in the hall.'),
('L1',7,'floor','noun','general','home','바닥; 층','The toy is on the floor.'),
('L1',8,'wall','noun','general','home','벽','There is a small picture on the wall.'),
('L1',9,'kitchen','noun','general','home','부엌','My father is in the kitchen.'),
('L1',10,'garden','noun','general','nature','정원','We grow tomatoes in the garden.'),
('L1',11,'milk','noun','general','food','우유','The child drinks milk every morning.'),
('L1',12,'egg','noun','general','food','달걀','I boiled an egg for breakfast.'),
('L1',13,'fish','noun','general','food','생선; 물고기','The fish is swimming in the pond.'),
('L1',14,'banana','noun','general','food','바나나','She packed a banana for a snack.'),
('L1',15,'lunch','noun','general','food','점심','We eat lunch at noon.'),
('L1',16,'dinner','noun','general','food','저녁 식사','Dinner is ready in the kitchen.'),
('L1',17,'morning','noun','general','time','아침','I walk in the morning.'),
('L1',18,'night','noun','general','time','밤','The street is quiet at night.'),
('L1',19,'rain','noun','general','weather','비','The rain stopped before noon.'),
('L1',20,'snow','noun','general','weather','눈','The children played in the snow.'),
('L1',21,'sun','noun','general','weather','태양; 햇빛','The sun is bright today.'),
('L1',22,'sky','noun','general','nature','하늘','A bird is flying across the sky.'),
('L1',23,'tree','noun','general','nature','나무','That tree gives us shade.'),
('L1',24,'flower','noun','general','nature','꽃','This flower has a yellow center.'),
('L1',25,'dog','noun','general','animals','개','Our dog waits by the door.'),
('L1',26,'cat','noun','general','animals','고양이','The cat is under the chair.'),
('L1',27,'parent','noun','general','family','부모','A parent must sign this form.'),
('L1',28,'sister','noun','general','family','여자 형제; 누나; 언니; 여동생','My sister plays the piano.'),
('L1',29,'brother','noun','general','family','남자 형제; 형; 오빠; 남동생','My brother rides the bus to school.'),
('L1',30,'baby','noun','general','family','아기','The baby is smiling at her mother.'),
('L1',31,'doctor','noun','general','health','의사','The doctor checked my arm.'),
('L1',32,'nurse','noun','general','health','간호사','The nurse showed us the room.'),
('L1',33,'park','noun','general','leisure','공원','We meet our friends in the park.'),
('L1',34,'road','noun','general','travel','도로; 길','The road is wet after the rain.'),
('L1',35,'train','noun','general','travel','기차','The train arrives at six.'),
('L1',36,'station','noun','general','travel','역','Meet me outside the station.'),
('L1',37,'map','noun','general','travel','지도','This map shows the bus route.'),
('L1',38,'name','noun','general','people','이름','Please write your name here.'),
('L1',39,'question','noun','academic','education','질문','I have a question about the homework.'),
('L1',40,'answer','noun','academic','education','답; 대답','Her answer was easy to understand.'),
('L1',41,'line','noun','general','location','줄; 선','Please stand in line.'),
('L1',42,'picture','noun','academic','communication','그림; 사진','The picture shows a green hill.'),
('L1',43,'color','noun','academic','description','색','Blue is my favorite color.'),
('L1',44,'clean','adjective','general','home','깨끗한','The kitchen is clean now.'),
('L1',45,'long','adjective','general','description','긴','This road is too long for a walk.'),
('L1',46,'fast','adjective','general','movement','빠른','The train is fast and quiet.'),
('L1',47,'hungry','adjective','general','food','배고픈','I feel hungry after the game.'),
('L1',48,'thirsty','adjective','general','food','목이 마른','We feel thirsty after the walk.'),
('L1',49,'together','adverb','general','people','함께','The family eats together on Sundays.'),
('L1',50,'behind','preposition','general','location','~ 뒤에','The bicycle is behind the house.'),

('L2',1,'share','verb','general','people','나누다; 공유하다','We share one large table at lunch.'),
('L2',2,'follow','verb','general','movement','따라가다','Follow the signs to the museum.'),
('L2',3,'reach','verb','general','travel','도착하다; 닿다','We can reach the lake by bus.'),
('L2',4,'miss','verb','general','travel','놓치다; 그리워하다','Hurry, or we will miss the train.'),
('L2',5,'spend','verb','general','time','시간이나 돈을 쓰다','I spend an hour reading each evening.'),
('L2',6,'save','verb','general','money','저축하다; 절약하다','We save water by taking shorter showers.'),
('L2',7,'collect','verb','general','hobbies','모으다','He likes to collect postcards.'),
('L2',8,'deliver','verb','workplace','service','배달하다; 전달하다','The driver will deliver the package before noon.'),
('L2',9,'include','verb','academic','education','포함하다','The course will include a short speaking task.'),
('L2',10,'mean','verb','academic','communication','의미하다','What does this word mean?'),
('L2',11,'notice','verb','general','observation','알아차리다','Did you notice the sign near the entrance?'),
('L2',12,'visit','verb','general','travel','방문하다','We will visit the science museum tomorrow.'),
('L2',13,'village','noun','general','community','마을','The village has a small library.'),
('L2',14,'island','noun','general','travel','섬','They live on a quiet island.'),
('L2',15,'bridge','noun','general','travel','다리','The bridge crosses the wide river.'),
('L2',16,'corner','noun','general','location','모퉁이; 구석','The bakery is around the corner.'),
('L2',17,'direction','noun','general','travel','방향','Which direction leads to the station?'),
('L2',18,'schedule','noun','workplace','planning','일정; 시간표','The new schedule starts on Monday.'),
('L2',19,'holiday','noun','general','leisure','휴일; 휴가','We are planning a family holiday.'),
('L2',20,'passport','noun','general','travel','여권','Keep your passport in a safe place.'),
('L2',21,'suitcase','noun','general','travel','여행 가방','My suitcase has a broken wheel.'),
('L2',22,'market','noun','workplace','shopping','시장','The market opens before sunrise.'),
('L2',23,'noise','noun','general','environment','소음','The noise stopped when the machines were turned off.'),
('L2',24,'voice','noun','general','communication','목소리','Her voice was clear during the call.'),
('L2',25,'idea','noun','academic','reasoning','생각; 아이디어','That is a useful idea for the project.'),
('L2',26,'story','noun','academic','communication','이야기','The story has a surprising ending.'),
('L2',27,'forest','noun','general','nature','숲','A narrow path leads into the forest.'),
('L2',28,'river','noun','general','nature','강','The river flows past the village.'),
('L2',29,'field','noun','general','nature','들판; 분야','The children ran across the field.'),
('L2',30,'team','noun','workplace','organization','팀','Our team meets every Friday.'),
('L2',31,'member','noun','workplace','organization','구성원','Each member received a name badge.'),
('L2',32,'visitor','noun','workplace','service','방문객','Every visitor must sign at the front desk.'),
('L2',33,'worker','noun','workplace','employment','근로자; 노동자','The worker repaired the broken gate.'),
('L2',34,'driver','noun','workplace','travel','운전자','The driver stopped near the hotel.'),
('L2',35,'lesson','noun','academic','education','수업','The lesson begins with a short review.'),
('L2',36,'language','noun','academic','education','언어','Learning a new language takes patience.'),
('L2',37,'exercise','noun','general','health','운동; 연습','Gentle exercise can improve your mood.'),
('L2',38,'break','noun','workplace','time','휴식; 쉬는 시간','We take a short break at ten.'),
('L2',39,'kind','adjective','general','people','친절한; 다정한','The kind guide answered every question.'),
('L2',40,'noisy','adjective','general','environment','시끄러운','The street is noisy during the festival.'),
('L2',41,'quiet','adjective','general','description','조용한','I prefer a quiet place to study.'),
('L2',42,'safe','adjective','general','health','안전한','This path is safe for children.'),
('L2',43,'useful','adjective','academic','education','유용한','The chart is useful for beginners.'),
('L2',44,'famous','adjective','general','culture','유명한','The city is famous for its old bridge.'),
('L2',45,'different','adjective','general','decisions','다른; 서로 다른','We chose a different route home.'),
('L2',46,'simple','adjective','academic','education','간단한','The teacher gave us a simple example.'),
('L2',47,'often','adverb','general','habits','자주','I often cook dinner with my family.'),
('L2',48,'never','adverb','general','habits','결코 ~않다','He never leaves his phone on the table.'),
('L2',49,'already','adverb','general','time','이미','The bus has already arrived.'),
('L2',50,'between','preposition','general','location','~ 사이에','The cafe is between the bank and the station.'),

('L3',1,'accept','verb','workplace','communication','받아들이다; 수락하다','The editor will accept the final draft on Friday.'),
('L3',2,'apply','verb','workplace','employment','지원하다; 적용하다','She will apply for the design internship.'),
('L3',3,'attend','verb','academic','education','참석하다','Many students attend the evening lecture.'),
('L3',4,'belong','verb','general','people','~에 속하다','These books belong to the community center.'),
('L3',5,'communicate','verb','workplace','communication','의사소통하다','Teams communicate through a shared calendar.'),
('L3',6,'connect','verb','general','technology','연결하다','The new path connects the village to the station.'),
('L3',7,'create','verb','academic','production','만들다; 창조하다','The class will create a poster about recycling.'),
('L3',8,'discover','verb','academic','research','발견하다','The researchers hope to discover a pattern in the data.'),
('L3',9,'discuss','verb','academic','communication','논의하다','We will discuss the results after lunch.'),
('L3',10,'encounter','verb','general','travel','마주치다; 맞닥뜨리다','Travelers may encounter delays during winter.'),
('L3',11,'examine','verb','academic','research','조사하다; 검토하다','The report will examine changes in local rainfall.'),
('L3',12,'focus','verb','academic','education','집중하다','Please focus on the main question.'),
('L3',13,'handle','verb','workplace','operations','처리하다; 다루다','The help desk can handle simple account requests.'),
('L3',14,'influence','verb','general','society','영향을 미치다','Weather can influence how people travel.'),
('L3',15,'inspire','verb','general','culture','영감을 주다','The mural may inspire young artists.'),
('L3',16,'measure','verb','academic','research','측정하다','The device can measure room temperature.'),
('L3',17,'observe','verb','academic','research','관찰하다','Students observe birds from the shelter.'),
('L3',18,'perform','verb','workplace','operations','수행하다; 공연하다','The technician will perform a safety check.'),
('L3',19,'protect','verb','general','environment','보호하다','Trees protect the soil from heavy rain.'),
('L3',20,'reflect','verb','academic','reasoning','반영하다; 숙고하다','The survey results reflect changing habits.'),
('L3',21,'select','verb','workplace','planning','선택하다; 선발하다','Please select one topic for your presentation.'),
('L3',22,'vary','verb','academic','research','달라지다; 다양하다','Prices vary by season and location.'),
('L3',23,'volunteer','verb','general','community','자원봉사하다; 자원하다','Many residents volunteer at the food bank.'),
('L3',24,'access','noun','academic','technology','접근; 이용 권한','Students need internet access for the assignment.'),
('L3',25,'challenge','noun','general','decisions','어려운 과제; 도전','Learning to present ideas is a useful challenge.'),
('L3',26,'culture','noun','general','society','문화','Food is an important part of local culture.'),
('L3',27,'decision','noun','general','decisions','결정','The committee reached a decision after the meeting.'),
('L3',28,'feature','noun','academic','description','특징; 특색','The map has a feature that marks bike lanes.'),
('L3',29,'goal','noun','academic','education','목표','Her goal is to finish the course.'),
('L3',30,'habit','noun','general','habits','습관','A short walk is a healthy habit.'),
('L3',31,'method','noun','academic','research','방법','This method uses interviews and simple notes.'),
('L3',32,'pattern','noun','academic','research','패턴; 양식','The chart reveals a clear pattern.'),
('L3',33,'project','noun','workplace','planning','프로젝트; 계획','Our project connects three neighborhood gardens.'),
('L3',34,'quality','noun','workplace','business','품질; 질','The factory checks the quality of every item.'),
('L3',35,'relationship','noun','general','people','관계','Trust is important in a strong relationship.'),
('L3',36,'solution','noun','academic','reasoning','해결책','The group found a practical solution.'),
('L3',37,'source','noun','academic','research','출처; 원천','The article names the source of each number.'),
('L3',38,'success','noun','general','decisions','성공','Small steps can lead to success.'),
('L3',39,'task','noun','workplace','operations','과업; 할 일','Finish the first task before the break.'),
('L3',40,'value','noun','general','decisions','가치; 중요성','The museum explains the value of local history.'),
('L3',41,'active','adjective','general','health','활동적인; 적극적인','An active lifestyle can support good health.'),
('L3',42,'creative','adjective','academic','production','창의적인','The students proposed a creative way to reuse boxes.'),
('L3',43,'effective','adjective','workplace','operations','효과적인','The new sign is an effective reminder.'),
('L3',44,'formal','adjective','workplace','communication','공식적인; 격식 있는','The letter uses formal language.'),
('L3',45,'independent','adjective','academic','education','독립적인','The learners completed an independent research task.'),
('L3',46,'rare','adjective','general','nature','드문; 희귀한','This bird is rare in the city.'),
('L3',47,'serious','adjective','general','health','심각한; 진지한','The clinic treats serious injuries.'),
('L3',48,'however','adverb','academic','reasoning','그러나; 하지만','The route is longer; however, it is safer.'),
('L3',49,'according to','phrase','academic','research','~에 따르면','According to the chart, evening use is increasing.'),
('L3',50,'throughout','preposition','general','time','~ 내내; 도처에','The lights remained on throughout the night.'),

('L4',1,'administer','verb','workplace','operations','관리하다; 시행하다','A nurse will administer the new survey to each participant.'),
('L4',2,'advocate','verb','general','community','지지하다; 옹호하다','Several residents advocate safer crossings near the school.'),
('L4',3,'assemble','verb','workplace','operations','조립하다; 모으다','The technicians will assemble the equipment on site.'),
('L4',4,'attain','verb','academic','education','달성하다','The program helps learners attain a higher level of accuracy.'),
('L4',5,'calculate','verb','academic','research','계산하다','The spreadsheet can calculate the average response time.'),
('L4',6,'collaborate','verb','workplace','organization','협력하다','The two laboratories collaborate on water research.'),
('L4',7,'compile','verb','academic','research','편집하여 모으다','The analyst will compile the comments into a report.'),
('L4',8,'comprehend','verb','academic','comprehension','이해하다','Readers must comprehend the instructions before starting.'),
('L4',9,'constitute','verb','academic','reasoning','구성하다; ~을 이루다','These three sections constitute the main argument.'),
('L4',10,'consume','verb','general','environment','소비하다','Large buildings consume less energy after the upgrade.'),
('L4',11,'convert','verb','workplace','operations','전환하다; 바꾸다','The project will convert an empty lot into a garden.'),
('L4',12,'decline','verb','workplace','business','감소하다; 거절하다','Sales began to decline after the road closed.'),
('L4',13,'detect','verb','academic','research','발견하다; 감지하다','The sensor can detect a small change in pressure.'),
('L4',14,'eliminate','verb','workplace','operations','제거하다','The filter helps eliminate dust from the air.'),
('L4',15,'ensure','verb','workplace','policy','보장하다; 확실히 하다','A checklist helps ensure that no step is missed.'),
('L4',16,'expose','verb','academic','research','노출하다; 드러내다','The experiment may expose weaknesses in the model.'),
('L4',17,'generate','verb','workplace','business','생성하다; 발생시키다','Solar panels generate power on clear days.'),
('L4',18,'illustrate','verb','academic','communication','설명하다; 예를 들다','The diagram illustrates how water moves through the system.'),
('L4',19,'incorporate','verb','academic','education','포함하다; 통합하다','The revised lesson will incorporate a short debate.'),
('L4',20,'modify','verb','workplace','operations','수정하다; 변경하다','We need to modify the schedule after the delay.'),
('L4',21,'monitor','verb','workplace','operations','관찰하다; 감시하다','Staff monitor air quality near the construction site.'),
('L4',22,'perceive','verb','academic','reasoning','인식하다; 지각하다','People may perceive the same color in different ways.'),
('L4',23,'pursue','verb','academic','education','추구하다; 계속하다','She plans to pursue further study in design.'),
('L4',24,'regulate','verb','workplace','policy','규제하다; 조절하다','The agency will regulate the use of shared data.'),
('L4',25,'transform','verb','general','change','변형시키다; 바꾸다','The new line could transform travel across the region.'),
('L4',26,'verify','verb','workplace','operations','확인하다; 검증하다','Please verify the figures before publishing the report.'),
('L4',27,'withdraw','verb','workplace','business','철회하다; 인출하다','The applicant may withdraw the request before review.'),
('L4',28,'agenda','noun','workplace','planning','의제; 안건','The first item on the agenda concerns staff training.'),
('L4',29,'asset','noun','workplace','business','자산; 강점','The community garden is a valuable asset for the neighborhood.'),
('L4',30,'context','noun','academic','reasoning','맥락; 배경','The quote is clearer when read in context.'),
('L4',31,'contract','noun','workplace','employment','계약','Both sides signed the contract after negotiation.'),
('L4',32,'framework','noun','academic','reasoning','체계; 틀','The framework gives the study a clear structure.'),
('L4',33,'guideline','noun','workplace','policy','지침','The guideline explains how to store sensitive files.'),
('L4',34,'indicator','noun','academic','research','지표; 표시','Attendance is one indicator of interest in the course.'),
('L4',35,'insight','noun','academic','research','통찰; 이해','The interview offered insight into commuter choices.'),
('L4',36,'issue','noun','general','community','문제; 쟁점','The council discussed the issue at the public meeting.'),
('L4',37,'policy','noun','workplace','policy','정책; 방침','The policy limits personal use of company vehicles.'),
('L4',38,'process','noun','workplace','operations','과정; 절차','The hiring process takes about three weeks.'),
('L4',39,'risk','noun','general','health','위험','Wearing a helmet reduces the risk of injury.'),
('L4',40,'strategy','noun','academic','reasoning','전략','The team developed a strategy for comparing results.'),
('L4',41,'complex','adjective','academic','reasoning','복잡한','The system is complex but easy to navigate.'),
('L4',42,'innovative','adjective','workplace','business','혁신적인','The startup proposed an innovative recycling service.'),
('L4',43,'internal','adjective','workplace','organization','내부의','The memo describes an internal training program.'),
('L4',44,'legal','adjective','workplace','policy','법률상의; 합법적인','The agreement sets out the legal duties of each party.'),
('L4',45,'ongoing','adjective','workplace','operations','진행 중인','The ongoing repairs may affect bus service.'),
('L4',46,'practical','adjective','general','decisions','실용적인','We need a practical answer before Friday.'),
('L4',47,'regional','adjective','general','community','지역의','The library serves several regional schools.'),
('L4',48,'stable','adjective','academic','research','안정적인','The results remained stable across two tests.'),
('L4',49,'visible','adjective','general','description','보이는','The sign is visible from the main road.'),
('L4',50,'voluntary','adjective','general','community','자발적인; 자원봉사의','Participation in the cleanup is voluntary.'),

('L5',1,'acquire','verb','academic','education','습득하다; 획득하다','Learners acquire new strategies through regular practice.'),
('L5',2,'approximate','verb','academic','research','~에 가까운; 추정하다','The first calculation approximates the cost of the repair.'),
('L5',3,'assert','verb','academic','communication','주장하다; 단언하다','The author asserts that public space improves well-being.'),
('L5',4,'cease','verb','workplace','operations','중단하다','The factory will cease production during the inspection.'),
('L5',5,'coincide','verb','academic','research','동시에 일어나다; 일치하다','The festival will coincide with the opening of the new gallery.'),
('L5',6,'derive','verb','academic','reasoning','~에서 이끌어 내다','The researchers derive the estimate from three surveys.'),
('L5',7,'fluctuate','verb','workplace','business','변동하다','Energy prices fluctuate throughout the year.'),
('L5',8,'formulate','verb','academic','reasoning','공식화하다; 만들어 내다','The group will formulate a testable question.'),
('L5',9,'inhibit','verb','general','health','억제하다; 방해하다','Poor lighting can inhibit concentration.'),
('L5',10,'manipulate','verb','academic','research','조작하다; 능숙하게 다루다','The study tests whether framing can manipulate viewer choices.'),
('L5',11,'mediate','verb','workplace','communication','중재하다','A trained facilitator will mediate the discussion.'),
('L5',12,'overcome','verb','general','change','극복하다','The team overcame several technical problems.'),
('L5',13,'persist','verb','general','habits','지속되다; 고집하다','If the symptoms persist, contact the clinic.'),
('L5',14,'presume','verb','academic','reasoning','추정하다; 당연히 여기다','We should not presume that silence means agreement.'),
('L5',15,'prompt','verb','workplace','communication','촉발하다; 유도하다','The question prompted a lively discussion.'),
('L5',16,'render','verb','academic','communication','~하게 만들다; 표현하다','The diagram renders the process easier to follow.'),
('L5',17,'restore','verb','workplace','operations','복구하다; 회복시키다','Workers hope to restore power before evening.'),
('L5',18,'underlie','verb','academic','reasoning','~의 기초가 되다','Several assumptions underlie the proposed explanation.'),
('L5',19,'utilize','verb','workplace','operations','활용하다','The center will utilize unused rooms for evening classes.'),
('L5',20,'withstand','verb','workplace','operations','견디다','The bridge must withstand strong coastal winds.'),
('L5',21,'dilemma','noun','general','decisions','딜레마; 곤란한 선택','The committee faced a dilemma about closing the old clinic.'),
('L5',22,'hypothesis','noun','academic','research','가설','The experiment was designed to test the hypothesis.'),
('L5',23,'intervention','noun','general','health','개입; 중재','Early intervention can improve reading confidence.'),
('L5',24,'mechanism','noun','academic','research','작동 원리; 기제','The paper explains the mechanism behind the change.'),
('L5',25,'parameter','noun','academic','research','매개 변수; 기준 범위','The model has a parameter for seasonal demand.'),
('L5',26,'phenomenon','noun','academic','research','현상','The researchers documented the unusual phenomenon.'),
('L5',27,'prevalence','noun','academic','health','유병률; 널리 퍼짐','The report examines the prevalence of screen fatigue.'),
('L5',28,'protocol','noun','workplace','operations','공식 절차; 규약','The laboratory follows a strict safety protocol.'),
('L5',29,'sequence','noun','academic','reasoning','순서; 연속','The software records the sequence of user actions.'),
('L5',30,'trajectory','noun','academic','change','궤적; 진행 경로','The chart traces the career trajectory of the program.'),
('L5',31,'welfare','noun','general','society','복지; 안녕','The policy aims to protect the welfare of children.'),
('L5',32,'workload','noun','workplace','employment','업무량','The new schedule reduced the team workload.'),
('L5',33,'arbitrary','adjective','academic','reasoning','자의적인; 근거 없이 정한','The boundary is not arbitrary; it follows a clear rule.'),
('L5',34,'compatible','adjective','workplace','technology','호환되는; 양립할 수 있는','The new software is compatible with older devices.'),
('L5',35,'empirical','adjective','academic','research','경험적; 관찰에 근거한','The claim needs empirical support from a larger sample.'),
('L5',36,'ethical','adjective','general','society','윤리적인','The panel considered the ethical effects of the proposal.'),
('L5',37,'mutual','adjective','workplace','communication','상호 간의','The agreement is based on mutual respect.'),
('L5',38,'notable','adjective','academic','research','주목할 만한','The report records a notable increase in attendance.'),
('L5',39,'selective','adjective','academic','education','선택적인; 선별적인','The archive has a selective collection of local newspapers.'),
('L5',40,'straightforward','adjective','general','communication','간단하고 명확한','The instructions are straightforward enough for new users.'),
('L5',41,'widespread','adjective','general','society','널리 퍼진','The survey found widespread support for the park.'),
('L5',42,'accordingly','adverb','academic','reasoning','그에 따라','The evidence was limited; accordingly, the conclusion remains cautious.'),
('L5',43,'conversely','adverb','academic','reasoning','반대로','The first method saves time; conversely, the second provides more detail.'),
('L5',44,'notably','adverb','academic','communication','특히; 눈에 띄게','Notably, the largest changes occurred in rural areas.'),
('L5',45,'approximately','adverb','academic','research','대략; 약','The repair took approximately three hours.'),
('L5',46,'thereby','adverb','academic','reasoning','그것에 의해; 그 결과','The update reduced errors, thereby improving the user experience.'),
('L5',47,'via','preposition','workplace','travel','~을 통해','The samples were shipped via a refrigerated vehicle.'),
('L5',48,'akin','adjective','academic','reasoning','~와 유사한','The new approach is akin to a careful trial.'),
('L5',49,'offset','verb','workplace','business','상쇄하다','Tree planting can offset part of the building emissions.'),
('L5',50,'incur','verb','workplace','business','발생시키다; 부담하다','Late changes may incur an additional fee.'),

('L6',1,'aggregate','verb','academic','research','종합하다; 합계 내다','The analyst will aggregate results from five sites.'),
('L6',2,'appraise','verb','workplace','business','평가하다','The buyer will appraise the building before making an offer.'),
('L6',3,'ascertain','verb','academic','research','확인하여 알아내다','The survey cannot ascertain why some participants left.'),
('L6',4,'catalyze','verb','general','change','촉진하다','A small grant can catalyze new projects in the neighborhood.'),
('L6',5,'contextualize','verb','academic','communication','맥락화하다','The introduction contextualizes the debate with a brief history.'),
('L6',6,'deconstruct','verb','academic','reasoning','구조를 분석하다','The essay deconstructs the language of the advertisement.'),
('L6',7,'curtail','verb','workplace','operations','축소하다; 줄이다','The city may curtail water use during the drought.'),
('L6',8,'decentralize','verb','workplace','organization','분산시키다','The reform will decentralize decisions across regional offices.'),
('L6',9,'extrapolate','verb','academic','research','외삽하다','It is risky to extrapolate from such a small sample.'),
('L6',10,'operationalize','verb','academic','research','실행 가능한 방식으로 구체화하다','The team must operationalize the concept before collecting data.'),
('L6',11,'preclude','verb','workplace','policy','미리 막다; 배제하다','A missing permit may preclude the event from opening.'),
('L6',12,'rectify','verb','workplace','operations','바로잡다','The supplier promised to rectify the error within two days.'),
('L6',13,'replenish','verb','workplace','operations','보충하다','Staff replenish the shelves before the store opens.'),
('L6',14,'simulate','verb','academic','research','모의 실험하다','The program can simulate traffic under different conditions.'),
('L6',15,'stipulate','verb','workplace','policy','명시하다; 규정하다','The contract stipulates how disputes will be handled.'),
('L6',16,'transcend','verb','academic','reasoning','초월하다; 뛰어넘다','The message transcends the boundaries of one language.'),
('L6',17,'triangulate','verb','academic','research','여러 자료로 교차 검증하다','Researchers triangulate interviews with attendance records.'),
('L6',18,'wield','verb','general','communication','능숙하게 사용하다; 행사하다','The speaker wields humor to make a difficult point memorable.'),
('L6',19,'avert','verb','workplace','policy','피하다; 막다','Early warnings helped avert a larger service failure.'),
('L6',20,'codify','verb','workplace','governance','법전화하다; 체계화하다','The committee will codify the rules in a public handbook.'),
('L6',21,'disseminate','verb','academic','communication','퍼뜨리다; 보급하다','The center will disseminate the findings through public talks.'),
('L6',22,'paradigm','noun','academic','reasoning','사고방식; 패러다임','The discovery challenged the prevailing scientific paradigm.'),
('L6',23,'paradox','noun','academic','reasoning','역설','The policy presents a paradox: more choice can create more confusion.'),
('L6',24,'taxonomy','noun','academic','research','분류 체계','The article proposes a taxonomy of learning strategies.'),
('L6',25,'synthesis','noun','academic','research','종합; 통합','The final chapter offers a synthesis of the major arguments.'),
('L6',26,'inference','noun','academic','reasoning','추론; 추정','That inference depends on an assumption about timing.'),
('L6',27,'derivative','noun','academic','research','파생물; 도출된 것','The formula produces a derivative for each point.'),
('L6',28,'magnitude','noun','academic','research','규모; 크기','The study measures the magnitude of the seasonal change.'),
('L6',29,'threshold','noun','general','health','한계점; 기준점','The sensor activates when the temperature crosses a threshold.'),
('L6',30,'spectrum','noun','academic','research','범위; 스펙트럼','The survey covers a broad spectrum of opinions.'),
('L6',31,'adaptive','adjective','general','change','적응력이 있는','Adaptive planning helps communities respond to uncertainty.'),
('L6',32,'causal','adjective','academic','research','인과 관계의','The data do not prove a causal link.'),
('L6',33,'cumulative','adjective','academic','research','누적되는','The cumulative effect became visible after several months.'),
('L6',34,'dynamic','adjective','general','society','역동적인; 끊임없이 변하는','The city has a dynamic cultural scene.'),
('L6',35,'rigorous','adjective','academic','research','엄격한; 철저한','The journal requires rigorous evidence.'),
('L6',36,'salient','adjective','academic','communication','가장 두드러진','The report highlights the most salient differences.'),
('L6',37,'systemic','adjective','workplace','governance','시스템 전체의; 구조적인','The audit found a systemic weakness in the process.'),
('L6',38,'volatile','adjective','workplace','business','변동이 심한','The market remains volatile during the transition.'),
('L6',39,'viable','adjective','workplace','planning','실행 가능한','The team needs a viable plan for winter.'),
('L6',40,'intrinsic','adjective','academic','reasoning','본질적인; 고유한','The debate concerns the intrinsic value of public art.'),
('L6',41,'henceforth','adverb','workplace','policy','이제부터','Henceforth, all visitors must wear an identification badge.'),
('L6',42,'intrinsically','adverb','academic','reasoning','본질적으로','The two goals are not intrinsically opposed.'),
('L6',43,'namely','adverb','academic','communication','즉; 다시 말해','One issue remains, namely the lack of storage.'),
('L6',44,'per se','phrase','academic','reasoning','그 자체로','The tool is not harmful per se; its use matters.'),
('L6',45,'concomitant','adjective','academic','research','수반되는','The treatment produced a concomitant change in appetite.'),
('L6',46,'ancillary','adjective','workplace','operations','부수적인; 보조적인','The report includes ancillary costs such as printing.'),
('L6',47,'latent','adjective','academic','research','잠재된; 드러나지 않은','The analysis seeks to reveal latent preferences.'),
('L6',48,'arguably','adverb','academic','reasoning','주장하건대; 틀림없이','Arguably, the simplest model is the most useful.'),
('L6',49,'simultaneously','adverb','general','time','동시에','The two alarms rang simultaneously.'),
('L6',50,'therein','adverb','academic','communication','그 안에; 그 점에서','The contract contains a map; the delivery route is described therein.'),

('L7',1,'abrogate','verb','workplace','policy','폐지하다; 무효화하다','The legislature voted to abrogate the outdated rule.'),
('L7',2,'accede','verb','workplace','governance','동의하다; 요구를 받아들이다','The board may accede to the request after review.'),
('L7',3,'augment','verb','workplace','business','늘리다; 증대하다','The grant will augment the library budget.'),
('L7',4,'belie','verb','academic','communication','~을 거짓임을 보여 주다; 감추다','The calm surface belies the complexity below.'),
('L7',5,'buttress','verb','academic','reasoning','강화하다; 뒷받침하다','The new data buttress the original conclusion.'),
('L7',6,'circumscribe','verb','workplace','policy','제한하다; 경계를 정하다','The charter circumscribes the powers of the committee.'),
('L7',7,'crystallize','verb','academic','communication','구체화하다; 명확해지다','The discussion helped crystallize the main research question.'),
('L7',8,'decry','verb','general','society','공개적으로 비난하다','Residents decry the loss of the historic market.'),
('L7',9,'deplore','verb','general','society','개탄하다; 강하게 비판하다','Many citizens deplore the lack of affordable housing.'),
('L7',10,'espouse','verb','academic','communication','지지하다; 받아들이다','The essay espouses a cautious view of technological change.'),
('L7',11,'foment','verb','general','society','조장하다; 선동하다','Sensational headlines can foment distrust.'),
('L7',12,'galvanize','verb','general','community','자극하여 행동하게 하다','The discovery galvanized volunteers to restore the wetland.'),
('L7',13,'impel','verb','general','decisions','강하게 몰아붙이다; 촉구하다','A sense of fairness impelled her to report the error.'),
('L7',14,'inculcate','verb','academic','education','주입하다; 심어 주다','Good teachers inculcate respect for careful evidence.'),
('L7',15,'invoke','verb','workplace','policy','들다; 발동하다','The company may invoke the emergency clause.'),
('L7',16,'legitimize','verb','workplace','governance','정당화하다; 합법화하다','The review helped legitimize the new selection process.'),
('L7',17,'misconstrue','verb','academic','communication','잘못 해석하다','Readers may misconstrue the warning without its context.'),
('L7',18,'obfuscate','verb','academic','communication','모호하게 하다; 흐리다','Technical language can obfuscate a simple explanation.'),
('L7',19,'perpetuate','verb','general','society','영속시키다; 지속시키다','The policy could perpetuate unequal access to transport.'),
('L7',20,'preempt','verb','workplace','planning','선제적으로 막다; 선점하다','The team acted early to preempt a shortage of materials.'),
('L7',21,'proscribe','verb','workplace','policy','금지하다; 제한하다','The code proscribes sharing confidential records.'),
('L7',22,'repudiate','verb','academic','communication','거부하다; 부인하다','The author publicly repudiated the inaccurate quotation.'),
('L7',23,'rescind','verb','workplace','policy','철회하다; 폐지하다','The agency decided to rescind the temporary permit.'),
('L7',24,'surmise','verb','academic','reasoning','추측하다','From the empty room, we can only surmise what happened.'),
('L7',25,'subvert','verb','workplace','governance','전복하다; 체계를 약화시키다','False reports can subvert trust in a public service.'),
('L7',26,'transgress','verb','workplace','policy','규범을 위반하다','The contractor was fined for transgressing the safety code.'),
('L7',27,'usurp','verb','workplace','governance','권한을 부당하게 빼앗다','No department should usurp the authority of the review panel.'),
('L7',28,'vindicate','verb','academic','reasoning','정당성을 입증하다; 혐의를 벗기다','The later evidence may vindicate the original decision.'),
('L7',29,'warrant','verb','academic','reasoning','정당화하다; 필요로 하다','The results do not warrant such a broad conclusion.'),
('L7',30,'apportion','verb','workplace','planning','배분하다','The committee will apportion the budget among three programs.'),
('L7',31,'hegemony','noun','academic','society','패권; 지배','The essay examines the cultural hegemony of a major language.'),
('L7',32,'impetus','noun','general','change','자극; 추진력','The award gave the young team an impetus to continue.'),
('L7',33,'milieu','noun','general','society','환경; 사회적 분위기','The artist found a supportive milieu in the small city.'),
('L7',34,'proclivity','noun','general','people','경향; 성향','The survey measured proclivity for risk among participants.'),
('L7',35,'provenance','noun','academic','research','기원; 출처','The archive records the provenance of each photograph.'),
('L7',36,'scrutiny','noun','workplace','governance','면밀한 검토','The proposal will receive public scrutiny before approval.'),
('L7',37,'stasis','noun','academic','change','정체; 고착 상태','Without new investment, the industry may remain in stasis.'),
('L7',38,'zeitgeist','noun','general','culture','시대정신','The exhibition captures the environmental zeitgeist of the decade.'),
('L7',39,'abstruse','adjective','academic','reasoning','난해한; 이해하기 어려운','The article explains an abstruse idea with a simple diagram.'),
('L7',40,'belligerent','adjective','general','communication','호전적인; 공격적인','The speaker adopted a belligerent tone during the debate.'),
('L7',41,'circumspect','adjective','workplace','governance','신중한; 조심스러운','The manager was circumspect when discussing unverified figures.'),
('L7',42,'deleterious','adjective','general','health','해로운','Long-term sleep loss can have deleterious effects.'),
('L7',43,'immutable','adjective','academic','reasoning','변경할 수 없는; 불변의','The rules are not immutable and can be reviewed.'),
('L7',44,'inchoate','adjective','academic','production','형태가 잡히지 않은; 미숙한','The proposal is still inchoate but has promising ideas.'),
('L7',45,'insidious','adjective','general','health','서서히 해로운; 교묘한','The report warns of the insidious effects of indoor pollution.'),
('L7',46,'liminal','adjective','general','culture','경계에 있는; 과도기의','The station feels liminal between the old and new neighborhoods.'),
('L7',47,'ubiquitous','adjective','general','technology','어디에나 있는; 매우 흔한','Mobile payment is now ubiquitous in the city.'),
('L7',48,'vacuous','adjective','academic','communication','공허한; 내용 없는','The statement sounded impressive but remained vacuous.'),
('L7',49,'concomitantly','adverb','academic','reasoning','동시에; 수반하여','Costs rose and quality declined concomitantly.'),
('L7',50,'ipso facto','phrase','academic','reasoning','사실 그 자체로; 그 결과','Being popular does not ipso facto make an argument sound.')
)
insert into public.vocabulary_catalog(id,content_key,term,meaning,example,part_of_speech,difficulty,cefr_anchor,cefr_band,topics,domains,skills,priority,source,license,provenance)
select ('e2000000-0000-4000-8000-' || lpad(l.ordinal::text,2,'0') || lpad(c.seq::text,10,'0'))::uuid,
  'wl-exp2-' || lower(c.level) || '-' || lpad(c.seq::text,3,'0'),
  c.term,c.meaning,c.example,c.pos,c.level,l.cefr_anchor,l.cefr_band,
  array[c.topic],array[c.domain],
  case c.domain when 'workplace' then array['comprehension','conversation','toeic_listening','toeic_reading']
    when 'academic' then array['literacy','production','comprehension']
    else array['literacy','production','comprehension','conversation'] end,
  70,'WordLoop original editorial content','LicenseRef-WordLoop-Original',
  jsonb_build_object('method','original WordLoop AI-assisted editorial content; no imported course or dictionary text',
    'version','exp2','level_basis','editorial estimate, not certified CEFR classification',
    'review_status','initial editorial pass; not independently calibrated',
    'rights','Original project content; no third-party redistribution license asserted')
from cards c join public.difficulty_levels l on l.code = c.level;

-- Same transparent editorial rules as v1 and exp1, scoped only to exp2 cards and existing tracks.
with classified as (
  select c.id catalog_id,t.id track_id,
    case
      when t.code = 'det_120_plus' and c.difficulty = 'L5' then 'core'
      when t.code = 'det_120_plus' and c.difficulty = 'L6' then 'stretch'
      when t.code = 'toeic_750' and c.difficulty in ('L3','L4') then 'core'
      when t.code = 'toeic_750' and c.difficulty = 'L5' then 'stretch'
      when t.code = 'toeic_900' and c.difficulty in ('L4','L5') then 'core'
      when t.code = 'toeic_900' and c.difficulty = 'L6' then 'stretch'
      else 'optional' end role,
    case when t.exam = 'DET' then not ('workplace' = any(c.domains))
      else 'workplace' = any(c.domains) end domain_match
  from public.vocabulary_catalog c cross join public.learning_tracks t
  where c.content_key like 'wl-exp2-%' and t.code in ('det_120_plus','toeic_750','toeic_900')
)
insert into public.catalog_track_rules(catalog_id,track_id,role,priority,weight,rationale)
select catalog_id,track_id,role,
  (case role when 'core' then 80 when 'stretch' then 50 else 10 end) + case when domain_match then 10 else 0 end,
  (case role when 'core' then 1.0 when 'stretch' then 0.35 else 0.1 end) * case when domain_match then 1.2 else 1.0 end,
  'Editorial level rule; domain affinity adds priority. Optional means fallback, not automatic promotion.'
from classified;
