-- Original WordLoop starter content, v1. No scraped dictionary or proprietary course lists.
-- Data migrations run on existing installations too; local db.seed is intentionally disabled.
insert into public.difficulty_levels(code,ordinal,label,cefr_anchor,cefr_band,description,exam_guidance) values
('L1',1,'생활 기초','A1','A1–A2','눈앞의 사물과 일상 행동을 표현한다.','입문용 어휘. 시험 점수를 예측하지 않음.'),
('L2',2,'일상 확장','A2','A2','일정, 이동, 간단한 요청을 표현한다.','기초 보강용. 시험 점수를 예측하지 않음.'),
('L3',3,'중급 연결','B1','B1','경험과 선택의 이유를 설명한다.','TOEIC 750 준비의 기초 보강 범위(내부 추천).'),
('L4',4,'중상급 준비','B2','B1–B2','업무와 학습 상황에서 정보를 비교한다.','TOEIC 750 핵심 및 900 준비 범위(내부 추천).'),
('L5',5,'고급 핵심','B2','B2','근거와 주장을 정확한 어휘로 전달한다.','DET 120+ 및 TOEIC 900 핵심 추천. DET 공식 B2 범위는 100–125이나 L5와의 환산은 아님.'),
('L6',6,'고급 확장','C1','B2–C1','추상적 관계와 세밀한 차이를 설명한다.','DET 120+ 도전 추천. DET 공식 C1 범위는 130–150이나 L6와의 환산은 아님.'),
('L7',7,'정교한 표현','C1','C1–C2','격식 있는 논의에서 의미와 논리를 정교하게 다룬다.','상위 확장 어휘. 단어 학습만으로 고득점을 보장하지 않음.');

insert into public.learning_tracks(id,code,label,exam,target_score,core_level,stretch_level,description,exam_guidance) values
('a0000000-0000-4000-8000-000000000001','det_120_plus','DET 120+','DET',120,'L5','L6','일반·학술 맥락의 B2 핵심과 C1 도전 어휘를 연습한다.','목표 점수는 학습 방향이다. 120은 공식 B2 점수 범위 내에 있으며 WordLoop 난이도는 점수 환산표가 아니다.'),
('a0000000-0000-4000-8000-000000000002','toeic_750','TOEIC 750','TOEIC_LR',750,'L4','L5','일상·업무 맥락의 중급 어휘를 다지고 중상급 표현을 확장한다.','TOEIC L&R 750 목표를 위한 내부 추천. ETS는 듣기와 읽기별 CEFR 기준을 제시하며 총점으로 개인 수준을 단정하지 않는다.'),
('a0000000-0000-4000-8000-000000000003','toeic_900','TOEIC 900','TOEIC_LR',900,'L5','L6','업무 문서와 설명의 정확한 이해를 위해 어휘 폭을 넓힌다.','TOEIC L&R 900 목표를 위한 내부 추천. 학습 난이도와 시험 점수는 공식적으로 환산되지 않는다.');

-- Sequence numbers are permanent content identifiers, not measured frequency ranks.
with cards(level,seq,term,pos,domain,topic,meaning,example) as (values
('L1',1,'water','noun','general','home','마시는 물','Please bring a glass of water.'),
('L1',2,'bread','noun','general','food','빵','We bought fresh bread for breakfast.'),
('L1',3,'room','noun','general','home','방','My room has a small window.'),
('L1',4,'door','noun','general','home','문','Please close the door quietly.'),
('L1',5,'family','noun','general','people','가족','My family eats dinner together.'),
('L1',6,'friend','noun','general','people','친구','My friend lives near the park.'),
('L1',7,'school','noun','academic','education','학교','The school is next to the library.'),
('L1',8,'book','noun','academic','education','책','This book has pictures of animals.'),
('L1',9,'desk','noun','workplace','office','책상','Put the notebook on my desk.'),
('L1',10,'work','verb','workplace','employment','일하다','I work in a small shop.'),
('L1',11,'read','verb','academic','education','읽다','We read a short story every morning.'),
('L1',12,'write','verb','academic','education','쓰다','Please write your name here.'),
('L1',13,'listen','verb','general','communication','귀 기울여 듣다','I listen to music on the bus.'),
('L1',14,'speak','verb','general','communication','말하다','Can you speak a little more slowly?'),
('L1',15,'walk','verb','general','travel','걷다','We walk to the station together.'),
('L1',16,'open','verb','workplace','office','열다','Please open the window before the meeting.'),
('L1',17,'help','verb','general','people','돕다','Can you help me carry this box?'),
('L1',18,'buy','verb','general','shopping','사다','I need to buy some milk.'),
('L1',19,'small','adjective','general','description','작은','A small bag is enough for today.'),
('L1',20,'early','adverb','workplace','time','일찍','Please arrive early for work tomorrow.'),
('L1',21,'happy','adjective','general','feelings','행복한; 기쁜','I am happy to see you.'),
('L1',22,'tired','adjective','general','feelings','피곤한','She feels tired after the long walk.'),
('L1',23,'today','adverb','general','time','오늘','We are staying at home today.'),
('L1',24,'near','preposition','general','location','~ 가까이에','There is a bus stop near the office.'),
('L1',25,'price','noun','workplace','shopping','가격','What is the price of this chair?'),

('L2',1,'borrow','verb','academic','education','빌리다','May I borrow your dictionary until Friday?'),
('L2',2,'return','verb','general','shopping','돌려주다; 반납하다','Please return the keys before you leave.'),
('L2',3,'choose','verb','general','decisions','고르다','You can choose a seat by the window.'),
('L2',4,'invite','verb','general','people','초대하다','We plan to invite our neighbors to dinner.'),
('L2',5,'arrive','verb','general','travel','도착하다','The train will arrive in ten minutes.'),
('L2',6,'leave','verb','general','travel','떠나다; 출발하다','We should leave before the roads get busy.'),
('L2',7,'carry','verb','workplace','office','나르다; 들고 가다','Can you carry these folders upstairs?'),
('L2',8,'explain','verb','academic','education','설명하다','Could you explain the last question again?'),
('L2',9,'practice','verb','academic','education','연습하다','I practice English with a classmate after lunch.'),
('L2',10,'remember','verb','general','memory','기억하다','Do you remember the name of that cafe?'),
('L2',11,'forget','verb','general','memory','잊다','Do not forget to bring your ticket.'),
('L2',12,'healthy','adjective','general','health','건강한','A healthy breakfast helps me start the day.'),
('L2',13,'comfortable','adjective','general','home','편안한','These shoes are comfortable enough for a long walk.'),
('L2',14,'busy','adjective','workplace','employment','바쁜','The office is usually busy on Monday mornings.'),
('L2',15,'weather','noun','general','nature','날씨','The weather may change in the afternoon.'),
('L2',16,'journey','noun','general','travel','여행; 이동 여정','The journey to the island takes two hours.'),
('L2',17,'ticket','noun','general','travel','표; 승차권','Keep your ticket until you leave the station.'),
('L2',18,'customer','noun','workplace','service','손님; 고객','A customer is waiting near the front door.'),
('L2',19,'meeting','noun','workplace','office','회의','Our team has a meeting after lunch.'),
('L2',20,'message','noun','workplace','communication','메시지; 전달할 말','Please leave a message if I cannot answer.'),
('L2',21,'plan','noun','general','decisions','계획','Our plan is to visit the museum first.'),
('L2',22,'mistake','noun','academic','education','실수','I made a mistake in the second sentence.'),
('L2',23,'instead','adverb','general','decisions','그 대신에','The shop was closed, so we went home instead.'),
('L2',24,'usually','adverb','general','habits','보통; 대개','I usually check the weather before going out.'),
('L2',25,'book','verb','workplace','travel','예약하다','Please book a room for the visiting team.'),

('L3',1,'improve','verb','academic','education','개선하다; 향상시키다','Daily reading can improve your vocabulary.'),
('L3',2,'compare','verb','academic','reasoning','비교하다','Compare the two results before writing your answer.'),
('L3',3,'suggest','verb','workplace','communication','제안하다','I suggest moving the meeting to Thursday.'),
('L3',4,'decide','verb','general','decisions','결정하다','We need to decide which route to take.'),
('L3',5,'avoid','verb','general','decisions','피하다','Leave early to avoid the heavy traffic.'),
('L3',6,'allow','verb','workplace','policy','허용하다','The company will allow staff to work from home on Fridays.'),
('L3',7,'provide','verb','workplace','service','제공하다','The hotel will provide breakfast for all guests.'),
('L3',8,'expect','verb','general','planning','예상하다; 기대하다','We expect the repairs to take about a week.'),
('L3',9,'manage','verb','workplace','employment','관리하다; 운영하다','She will manage the new store.'),
('L3',10,'support','verb','general','people','지지하다; 돕다','Local volunteers support families during the winter.'),
('L3',11,'reduce','verb','general','environment','줄이다','Using a reusable bottle can reduce plastic waste.'),
('L3',12,'increase','verb','workplace','business','늘리다; 증가시키다','The shop hopes to increase sales this summer.'),
('L3',13,'experience','noun','general','people','경험','Working abroad was a valuable experience for her.'),
('L3',14,'opportunity','noun','workplace','employment','기회','The project is an opportunity to learn new skills.'),
('L3',15,'environment','noun','general','environment','환경','Small changes at home can help protect the environment.'),
('L3',16,'purpose','noun','academic','reasoning','목적','The purpose of this activity is to practice asking questions.'),
('L3',17,'result','noun','academic','research','결과','The result was different from our first guess.'),
('L3',18,'reason','noun','general','reasoning','이유','What was the main reason for your decision?'),
('L3',19,'available','adjective','workplace','service','이용 가능한; 구할 수 있는','A larger meeting room is available on Tuesday.'),
('L3',20,'responsible','adjective','workplace','employment','책임이 있는; 담당하는','Who is responsible for checking the equipment?'),
('L3',21,'local','adjective','general','community','지역의','We buy most of our vegetables at the local market.'),
('L3',22,'similar','adjective','academic','reasoning','비슷한','The two articles reach similar conclusions.'),
('L3',23,'although','conjunction','academic','reasoning','비록 ~이지만','Although the course was difficult, I enjoyed it.'),
('L3',24,'therefore','adverb','academic','reasoning','그러므로; 따라서','The road is closed; therefore, we must take another route.'),
('L3',25,'deadline','noun','workplace','planning','마감 기한','The deadline for applications is next Friday.'),

('L4',1,'analyze','verb','academic','research','분석하다','We need to analyze the survey responses before making a decision.'),
('L4',2,'evaluate','verb','academic','research','평가하다','The committee will evaluate each proposal using the same criteria.'),
('L4',3,'identify','verb','academic','research','찾아내다; 식별하다','The study aims to identify the causes of sleep problems.'),
('L4',4,'establish','verb','workplace','organization','설립하다; 구축하다','The partners plan to establish a training center.'),
('L4',5,'maintain','verb','workplace','operations','유지하다','Regular checks help maintain the quality of the equipment.'),
('L4',6,'require','verb','workplace','policy','필요로 하다; 요구하다','This position will require some international travel.'),
('L4',7,'involve','verb','academic','education','포함하다; 수반하다','The course will involve both group work and independent study.'),
('L4',8,'contribute','verb','general','community','기여하다','Everyone can contribute to a cleaner neighborhood.'),
('L4',9,'benefit','noun','workplace','employment','이점; 혜택','One benefit of flexible hours is a shorter commute.'),
('L4',10,'evidence','noun','academic','research','증거; 근거','We need more evidence before accepting the explanation.'),
('L4',11,'approach','noun','academic','reasoning','접근법; 처리 방식','A different approach may help solve the problem.'),
('L4',12,'factor','noun','academic','research','요인','Cost is only one factor in choosing a university.'),
('L4',13,'impact','noun','general','environment','영향','The new road may have a serious impact on local wildlife.'),
('L4',14,'resource','noun','academic','education','자원; 활용할 수 있는 자료','The online archive is a useful resource for students.'),
('L4',15,'significant','adjective','academic','research','중요한; 상당한','The change led to a significant reduction in waiting times.'),
('L4',16,'efficient','adjective','workplace','operations','효율적인','An efficient booking system saves time for staff and customers.'),
('L4',17,'reliable','adjective','general','technology','믿을 만한','We need a reliable internet connection for the lesson.'),
('L4',18,'flexible','adjective','workplace','employment','유연한; 조정 가능한','The team agreed on a flexible schedule.'),
('L4',19,'relevant','adjective','academic','research','관련 있는','Include only the information that is relevant to your argument.'),
('L4',20,'whereas','conjunction','academic','reasoning','반면에','The first study used interviews, whereas the second used surveys.'),
('L4',21,'despite','preposition','general','reasoning','~에도 불구하고','The event continued despite the heavy rain.'),
('L4',22,'negotiate','verb','workplace','business','협상하다','The company will negotiate a new contract with the supplier.'),
('L4',23,'confirm','verb','workplace','communication','확인하다; 확정하다','Please confirm your attendance by Wednesday.'),
('L4',24,'purchase','noun','workplace','shopping','구매; 구입한 물품','Keep the receipt as proof of purchase.'),
('L4',25,'approach','verb','general','travel','다가가다','Slow down as you approach the crossing.'),

('L5',1,'allocate','verb','workplace','planning','배분하다; 할당하다','The team will allocate more time to testing the new system.'),
('L5',2,'justify','verb','academic','reasoning','타당한 이유를 제시하다; 정당화하다','You need evidence to justify that conclusion.'),
('L5',3,'assess','verb','academic','research','평가하다; 판단하다','The researchers will assess how noise affects concentration.'),
('L5',4,'interpret','verb','academic','research','해석하다','Readers may interpret the same passage in different ways.'),
('L5',5,'demonstrate','verb','academic','reasoning','입증하다; 분명히 보여 주다','These results demonstrate the value of regular feedback.'),
('L5',6,'distinguish','verb','academic','reasoning','구별하다','It is important to distinguish a prediction from a proven fact.'),
('L5',7,'retain','verb','academic','education','유지하다; 기억해 두다','Short review sessions help learners retain new vocabulary.'),
('L5',8,'adapt','verb','general','change','적응하다; 맞게 바꾸다','Communities must adapt to changes in the local climate.'),
('L5',9,'emphasize','verb','academic','communication','강조하다','The report will emphasize the need for reliable public transport.'),
('L5',10,'assumption','noun','academic','reasoning','가정; 사실이라고 여기는 생각','The plan rests on the assumption that demand will remain stable.'),
('L5',11,'perspective','noun','general','reasoning','관점','Living in another country gave her a different perspective on education.'),
('L5',12,'implication','noun','academic','reasoning','함의; 예상되는 영향','One implication of the findings is that smaller classes may need different teaching methods.'),
('L5',13,'constraint','noun','workplace','planning','제약 조건','The main constraint is the amount of time available.'),
('L5',14,'alternative','noun','general','decisions','대안','Cycling is a practical alternative to driving for short trips.'),
('L5',15,'consistent','adjective','academic','research','일관된','The pattern was consistent across all three experiments.'),
('L5',16,'substantial','adjective','workplace','business','상당한 규모의','The repair will require a substantial investment.'),
('L5',17,'sustainable','adjective','general','environment','지속 가능한','The city is looking for sustainable ways to manage waste.'),
('L5',18,'feasible','adjective','workplace','planning','실행 가능한','The proposal is feasible if we extend the deadline.'),
('L5',19,'crucial','adjective','general','health','매우 중요한; 결정적인','Access to clean water is crucial for public health.'),
('L5',20,'nevertheless','adverb','academic','reasoning','그럼에도 불구하고','The sample was small; nevertheless, the findings raise useful questions.'),
('L5',21,'consequently','adverb','academic','reasoning','그 결과로','Several buses were canceled; consequently, many students arrived late.'),
('L5',22,'revenue','noun','workplace','business','수익금; 매출','Ticket revenue covers most of the cost of the festival.'),
('L5',23,'incentive','noun','workplace','employment','장려책; 동기를 주는 것','The company offers an incentive for staff who cycle to work.'),
('L5',24,'address','verb','general','community','문제 등을 다루다; 해결에 나서다','The council must address the shortage of affordable housing.'),
('L5',25,'conduct','verb','academic','research','수행하다; 실시하다','The students will conduct interviews with local residents.'),

('L6',1,'mitigate','verb','general','environment','완화하다; 피해를 줄이다','Planting trees can mitigate the effects of extreme heat in cities.'),
('L6',2,'substantiate','verb','academic','reasoning','증거로 뒷받침하다','The author uses several case studies to substantiate the claim.'),
('L6',3,'reconcile','verb','academic','reasoning','서로 다른 생각 등을 조화시키다','The model attempts to reconcile two conflicting explanations.'),
('L6',4,'infer','verb','academic','reasoning','추론하다','We cannot infer a causal relationship from this pattern alone.'),
('L6',5,'synthesize','verb','academic','research','종합하다','The review will synthesize findings from several independent studies.'),
('L6',6,'scrutinize','verb','workplace','governance','면밀히 검토하다','Auditors will scrutinize the records before approving the report.'),
('L6',7,'facilitate','verb','workplace','communication','원활하게 하다; 촉진하다','Clear instructions facilitate communication between departments.'),
('L6',8,'undermine','verb','general','community','약화시키다; 기반을 훼손하다','Repeated delays can undermine public trust in the service.'),
('L6',9,'attribute','verb','academic','research','~의 탓이나 덕으로 돌리다','We should not attribute every improvement to the new policy.'),
('L6',10,'nuance','noun','general','communication','미묘한 차이','The translation captures an important nuance in the original dialogue.'),
('L6',11,'discrepancy','noun','workplace','operations','불일치; 차이','There is a discrepancy between the invoice and the delivery record.'),
('L6',12,'trade-off','noun','general','decisions','하나를 얻기 위해 다른 것을 포기하는 관계','There is often a trade-off between convenience and privacy.'),
('L6',13,'consensus','noun','academic','reasoning','의견의 일치; 합의','The panel reached a consensus after reviewing the evidence.'),
('L6',14,'rationale','noun','workplace','planning','결정의 근거; 논리적 이유','The manager explained the rationale behind the revised schedule.'),
('L6',15,'ambiguity','noun','academic','communication','모호함; 여러 해석의 가능성','The wording leaves some ambiguity about who is responsible.'),
('L6',16,'plausible','adjective','academic','reasoning','그럴듯한; 타당해 보이는','This is a plausible explanation, but it still needs testing.'),
('L6',17,'inherent','adjective','academic','reasoning','본래 내재하는','Some uncertainty is inherent in long-term forecasts.'),
('L6',18,'robust','adjective','academic','research','견고한; 조건이 바뀌어도 신뢰할 만한','A robust conclusion should hold across different samples.'),
('L6',19,'preliminary','adjective','academic','research','예비의; 초기 단계의','The preliminary findings will guide the next round of interviews.'),
('L6',20,'disproportionate','adjective','general','society','비례에 맞지 않는; 지나치게 큰','The fees place a disproportionate burden on smaller businesses.'),
('L6',21,'notwithstanding','preposition','workplace','policy','~에도 불구하고','Notwithstanding the delays, the team expects to meet the final deadline.'),
('L6',22,'contingency','noun','workplace','planning','만일의 사태; 예상 가능한 비상 상황','The budget includes a reserve for any unforeseen contingency.'),
('L6',23,'accountability','noun','workplace','governance','설명하고 책임질 의무','Public reporting can strengthen accountability in local government.'),
('L6',24,'coherent','adjective','academic','communication','논리적으로 일관된','The essay presents a coherent argument for improving public transport.'),
('L6',25,'qualify','verb','academic','reasoning','주장에 조건이나 제한을 붙이다','The researchers qualify their conclusion by noting the small sample size.'),

('L7',1,'corroborate','verb','academic','research','추가 증거로 확증하다','Independent records corroborate the account given by the witness.'),
('L7',2,'elucidate','verb','academic','communication','명확하게 설명하다','The diagram helps elucidate the relationship between the variables.'),
('L7',3,'delineate','verb','workplace','governance','경계나 범위를 명확히 기술하다','The agreement will delineate the responsibilities of each partner.'),
('L7',4,'circumvent','verb','workplace','policy','규칙이나 장애물을 우회하다','The audit found attempts to circumvent the approval process.'),
('L7',5,'exacerbate','verb','general','environment','악화시키다','Poor drainage can exacerbate flooding after heavy rain.'),
('L7',6,'juxtapose','verb','academic','communication','대비를 위해 나란히 놓다','The exhibition will juxtapose historical maps with recent photographs.'),
('L7',7,'equivocate','verb','general','communication','모호한 말로 확답을 피하다','When asked about the missing funds, the director began to equivocate.'),
('L7',8,'conflate','verb','academic','reasoning','서로 다른 것을 하나로 혼동하다','The argument seems to conflate popularity with reliability.'),
('L7',9,'presuppose','verb','academic','reasoning','전제로 삼다','The proposal would presuppose access to reliable internet in every household.'),
('L7',10,'disentangle','verb','academic','research','복잡하게 얽힌 것을 풀어 구분하다','It is difficult to disentangle the effects of income and education.'),
('L7',11,'caveat','noun','academic','reasoning','주의해야 할 조건; 단서','There is one caveat: the estimate excludes maintenance costs.'),
('L7',12,'ramification','noun','general','society','파생되는 영향; 복잡한 결과','One unexpected ramification of the policy was a rise in rents nearby.'),
('L7',13,'dichotomy','noun','academic','reasoning','양분; 두 가지로 나누는 구도','The essay challenges the dichotomy between economic growth and environmental protection.'),
('L7',14,'tenet','noun','academic','reasoning','핵심 원칙; 신조','A central tenet of the approach is that evidence must remain open to challenge.'),
('L7',15,'anomaly','noun','academic','research','이례적인 현상; 이상치','The team investigated an anomaly in the final set of measurements.'),
('L7',16,'ephemeral','adjective','general','culture','아주 잠깐 지속되는','Online attention can be ephemeral, even for a widely shared story.'),
('L7',17,'pervasive','adjective','general','society','널리 퍼져 있는','The report examines the pervasive influence of advertising on daily life.'),
('L7',18,'equivocal','adjective','academic','research','분명하지 않은; 여러 해석이 가능한','The evidence remains equivocal because the studies use different measures.'),
('L7',19,'ostensible','adjective','workplace','governance','표면상 내세우는','The ostensible purpose of the visit was to discuss future cooperation.'),
('L7',20,'cogent','adjective','academic','reasoning','논리적이고 설득력 있는','She offered a cogent explanation for the unexpected result.'),
('L7',21,'inextricably','adverb','general','society','뗄 수 없을 정도로 밀접하게','Access to education is inextricably linked to wider social conditions.'),
('L7',22,'procurement','noun','workplace','operations','조달; 조직의 물품 구매','The procurement process requires suppliers to disclose potential conflicts of interest.'),
('L7',23,'fiduciary','adjective','workplace','governance','수탁자로서 신뢰와 책임을 지는','The trustees have a fiduciary duty to act in the interests of the beneficiaries.'),
('L7',24,'redress','noun','general','society','피해에 대한 구제; 시정','The policy gives customers a clear route to redress when complaints are ignored.'),
('L7',25,'parsimonious','adjective','academic','research','설명에 불필요한 가정이 적은; 간명한','A parsimonious model explains the data with fewer assumptions.')
)
insert into public.vocabulary_catalog(id,content_key,term,meaning,example,part_of_speech,difficulty,cefr_anchor,cefr_band,topics,domains,skills,priority,source,license,provenance)
select md5('wordloop-catalog-v1-' || c.level || '-' || c.seq)::uuid,
  'wl-v1-' || lower(c.level) || '-' || lpad(c.seq::text,3,'0'),
  c.term,c.meaning,c.example,c.pos,c.level,l.cefr_anchor,l.cefr_band,
  array[c.topic],array[c.domain],
  case c.domain when 'workplace' then array['comprehension','conversation','toeic_listening','toeic_reading']
    when 'academic' then array['literacy','production','comprehension']
    else array['literacy','production','comprehension','conversation'] end,
  70,'WordLoop original starter catalog','LicenseRef-WordLoop-Original',
  jsonb_build_object('method','original AI-assisted editorial content; no imported course or dictionary text',
    'version','1','level_basis','editorial estimate, not certified CEFR classification',
    'review_status','initial editorial pass; not independently calibrated',
    'rights','Original project content; no third-party redistribution license asserted')
from cards c join public.difficulty_levels l on l.code = c.level;

-- Transparent starter rules, not a personalized or empirically calibrated recommendation model.
with classified as (
  select c.id catalog_id,t.id track_id,
    case
      when t.code = 'det_120_plus' and c.difficulty = 'L5' then 'core'
      when t.code = 'det_120_plus' and c.difficulty = 'L6' then 'stretch'
      when t.code = 'toeic_750' and c.difficulty in ('L3','L4') then 'core'
      when t.code = 'toeic_750' and c.difficulty = 'L5' then 'stretch'
      when t.code = 'toeic_900' and c.difficulty in ('L4','L5') then 'core'
      when t.code = 'toeic_900' and c.difficulty = 'L6' then 'stretch'
      else 'optional' end role,
    case when t.exam = 'DET' then not ('workplace' = any(c.domains))
      else 'workplace' = any(c.domains) end domain_match
  from public.vocabulary_catalog c cross join public.learning_tracks t
  where c.content_key like 'wl-v1-%' and t.code in ('det_120_plus','toeic_750','toeic_900')
)
insert into public.catalog_track_rules(catalog_id,track_id,role,priority,weight,rationale)
select catalog_id,track_id,role,
  (case role when 'core' then 80 when 'stretch' then 50 else 10 end) + case when domain_match then 10 else 0 end,
  (case role when 'core' then 1.0 when 'stretch' then 0.35 else 0.1 end) * case when domain_match then 1.2 else 1.0 end,
  'Editorial level rule; domain affinity adds priority. Optional means fallback, not automatic promotion.'
from classified;
