-- Original WordLoop editorial expansion, exp3: 50 new cards per level.
-- Append-only content; no scraped dictionary or proprietary course text.
-- Permanent exp3 UUID namespace + level/sequence; never regenerate IDs after releveling.
with cards(level,seq,term,pos,domain,topic,meaning,example) as (values
('L1',1,'toy','noun','general','play','장난감','The child put the toy in the box.'),
('L1',2,'ball','noun','general','play','공','The red ball rolled under the chair.'),
('L1',3,'shirt','noun','general','clothing','셔츠','He wore a clean shirt to school.'),
('L1',4,'coat','noun','general','clothing','코트; 외투','Take your coat because the air is cold.'),
('L1',5,'sock','noun','general','clothing','양말','I found one sock under the bed.'),
('L1',6,'hand','noun','general','body','손','Please raise your hand.'),
('L1',7,'face','noun','general','body','얼굴','Wash your face before breakfast.'),
('L1',8,'hair','noun','general','body','머리카락','Her hair is wet after the shower.'),
('L1',9,'eye','noun','general','body','눈','A small piece of dust is in my eye.'),
('L1',10,'ear','noun','general','body','귀','The child covered one ear.'),
('L1',11,'mouth','noun','general','body','입','Open your mouth for the dentist.'),
('L1',12,'nose','noun','general','body','코','His nose is red in the cold air.'),
('L1',13,'foot','noun','general','body','발','My foot hurts after the long walk.'),
('L1',14,'plate','noun','general','food','접시','Put the sandwich on a plate.'),
('L1',15,'spoon','noun','general','food','숟가락','The baby held a spoon.'),
('L1',16,'fork','noun','general','food','포크','Use a fork for the salad.'),
('L1',17,'bottle','noun','general','food','병','This bottle is full of juice.'),
('L1',18,'box','noun','general','home','상자','The books are in a cardboard box.'),
('L1',19,'towel','noun','general','home','수건','Hang the towel beside the sink.'),
('L1',20,'soap','noun','general','home','비누','This soap smells like lemon.'),
('L1',21,'mirror','noun','general','home','거울','She looked in the mirror.'),
('L1',22,'candle','noun','general','home','양초','We lit a candle during the power cut.'),
('L1',23,'house','noun','general','home','집','Their house has a blue gate.'),
('L1',24,'street','noun','general','location','거리','The children crossed the street with an adult.'),
('L1',25,'car','noun','general','travel','자동차','My car is parked near the house.'),
('L1',26,'bike','noun','general','travel','자전거','She rides her bike to the park.'),
('L1',27,'umbrella','noun','general','weather','우산','Bring an umbrella; rain may start soon.'),
('L1',28,'breakfast','noun','general','food','아침 식사','We had breakfast before the trip.'),
('L1',29,'snack','noun','general','food','간식','I packed a snack for the bus ride.'),
('L1',30,'juice','noun','general','food','주스','The orange juice is in the fridge.'),
('L1',31,'salt','noun','general','food','소금','Add a little salt to the soup.'),
('L1',32,'sugar','noun','general','food','설탕','He takes no sugar in his tea.'),
('L1',33,'tomato','noun','general','food','토마토','This tomato is ripe.'),
('L1',34,'potato','noun','general','food','감자','We baked a potato for lunch.'),
('L1',35,'orange','noun','general','food','오렌지','She peeled an orange at the table.'),
('L1',36,'cookie','noun','general','food','쿠키','The child asked for one cookie.'),
('L1',37,'cake','noun','general','food','케이크','We shared a small cake.'),
('L1',38,'game','noun','general','leisure','게임','The game starts after dinner.'),
('L1',39,'music','noun','general','leisure','음악','Soft music filled the room.'),
('L1',40,'movie','noun','general','leisure','영화','We watched a funny movie at home.'),
('L1',41,'song','noun','general','leisure','노래','That song makes me smile.'),
('L1',42,'smile','noun','general','feelings','미소','His smile made the baby laugh.'),
('L1',43,'cry','verb','general','feelings','울다','Some babies cry when they are hungry.'),
('L1',44,'laugh','verb','general','feelings','웃다','We laugh at the silly game.'),
('L1',45,'run','verb','general','movement','달리다','The dog can run very fast.'),
('L1',46,'jump','verb','general','movement','뛰다','The children jump over a small line.'),
('L1',47,'swim','verb','general','leisure','수영하다','They swim in the pool every Sunday.'),
('L1',48,'sing','verb','general','leisure','노래하다','We sing a song together.'),
('L1',49,'tall','adjective','general','description','키가 큰','The tall tree stands by the house.'),
('L1',50,'warm','adjective','general','weather','따뜻한','The soup is warm.'),

('L2',1,'pack','verb','general','travel','짐을 싸다; 챙기다','Please pack a sweater for the trip.'),
('L2',2,'fix','verb','general','home','고치다','Can you fix the loose handle?'),
('L2',3,'order','verb','general','shopping','주문하다','We order lunch from the cafe.'),
('L2',4,'cancel','verb','general','planning','취소하다','The airline may cancel the flight because of fog.'),
('L2',5,'change','verb','general','change','바꾸다; 변화시키다','I need to change my appointment.'),
('L2',6,'cross','verb','general','travel','건너다','Look both ways before you cross the road.'),
('L2',7,'climb','verb','general','movement','오르다','We climb the hill slowly.'),
('L2',8,'drive','verb','general','travel','운전하다','My uncle can drive us to the airport.'),
('L2',9,'ride','verb','general','travel','타다','She rides her bike to work.'),
('L2',10,'catch','verb','general','travel','잡다; (버스 등을) 타다','Hurry so you can catch the bus.'),
('L2',11,'feed','verb','general','family','먹이를 주다','Please feed the cat before school.'),
('L2',12,'grow','verb','general','nature','자라다; 재배하다','These plants grow well in sunlight.'),
('L2',13,'plant','verb','general','nature','심다','We plant flowers in the spring.'),
('L2',14,'move','verb','general','home','옮기다; 움직이다','Please move the box away from the door.'),
('L2',15,'mail','verb','workplace','communication','우편으로 보내다','I will mail the form tomorrow.'),
('L2',16,'print','verb','workplace','office','인쇄하다','Please print two copies of the schedule.'),
('L2',17,'copy','verb','academic','education','복사하다; 베껴 쓰다','Copy the sentence into your notebook.'),
('L2',18,'search','verb','academic','technology','검색하다; 찾다','We search the website for the answer.'),
('L2',19,'travel','verb','general','travel','여행하다; 이동하다','They travel by train in summer.'),
('L2',20,'relax','verb','general','leisure','쉬다; 긴장을 풀다','I relax with music after work.'),
('L2',21,'promise','verb','general','people','약속하다','I promise to call after dinner.'),
('L2',22,'event','noun','general','leisure','행사','The town holds an event in the park.'),
('L2',23,'festival','noun','general','culture','축제','The spring festival attracts many families.'),
('L2',24,'beach','noun','general','travel','해변','We walked along the beach at sunset.'),
('L2',25,'mountain','noun','general','nature','산','A tall mountain rose behind the village.'),
('L2',26,'lake','noun','general','nature','호수','The lake is calm in the morning.'),
('L2',27,'airport','noun','general','travel','공항','Our flight leaves from the main airport.'),
('L2',28,'hotel','noun','workplace','service','호텔','The hotel offers breakfast to guests.'),
('L2',29,'wallet','noun','general','shopping','지갑','I keep my bus card in my wallet.'),
('L2',30,'battery','noun','general','technology','배터리','The phone battery is almost empty.'),
('L2',31,'screen','noun','general','technology','화면; 스크린','The screen became dark after a minute.'),
('L2',32,'photo','noun','general','communication','사진','She sent a photo of the new garden.'),
('L2',33,'email','noun','workplace','communication','이메일','I received an email from the teacher.'),
('L2',34,'website','noun','workplace','technology','웹사이트','The company website lists opening hours.'),
('L2',35,'class','noun','academic','education','수업; 반','Our class begins at nine.'),
('L2',36,'cousin','noun','general','family','사촌','My cousin lives in another city.'),
('L2',37,'uncle','noun','general','family','삼촌; 외삼촌','My uncle grows vegetables.'),
('L2',38,'aunt','noun','general','family','이모; 고모; 숙모','My aunt baked a cake for us.'),
('L2',39,'adult','noun','general','people','성인','An adult must sign the permission form.'),
('L2',40,'gift','noun','general','people','선물','He bought a gift for his friend.'),
('L2',41,'problem','noun','general','reasoning','문제','We found a simple way to solve the problem.'),
('L2',42,'chance','noun','general','decisions','가능성; 기회','There is a good chance of rain tonight.'),
('L2',43,'rule','noun','workplace','policy','규칙','Everyone must follow the safety rule.'),
('L2',44,'dream','noun','general','feelings','꿈; 희망','Her dream is to visit another country.'),
('L2',45,'lucky','adjective','general','feelings','운이 좋은','We were lucky to find a taxi.'),
('L2',46,'careful','adjective','general','safety','조심하는; 주의 깊은','Be careful near the wet floor.'),
('L2',47,'friendly','adjective','general','people','친절한; 다정한','The friendly guide welcomed us.'),
('L2',48,'empty','adjective','general','description','비어 있는','The bottle is empty now.'),
('L2',49,'full','adjective','general','description','가득 찬','The bus is full of passengers.'),
('L2',50,'quickly','adverb','general','movement','빠르게','Please walk quickly to the station.'),

('L3',1,'arrange','verb','workplace','planning','마련하다; 정리하다','We will arrange the chairs before the workshop.'),
('L3',2,'behave','verb','general','people','행동하다','The children behaved well during the visit.'),
('L3',3,'compete','verb','workplace','business','경쟁하다','Small firms compete for skilled workers.'),
('L3',4,'complain','verb','general','service','불평하다; 항의하다','Customers may complain when the service is slow.'),
('L3',5,'depend','verb','general','decisions','의존하다; ~에 달려 있다','The final cost will depend on the distance.'),
('L3',6,'engage','verb','academic','education','참여하다; 관여시키다','The activity helps students engage with the text.'),
('L3',7,'preserve','verb','general','environment','보존하다','We should preserve the old trees near the river.'),
('L3',8,'promote','verb','workplace','business','촉진하다; 홍보하다','The campaign will promote local products.'),
('L3',9,'release','verb','workplace','business','출시하다; 공개하다','The publisher will release the report next week.'),
('L3',10,'reveal','verb','academic','research','드러내다; 밝히다','The interviews reveal a difference between the groups.'),
('L3',11,'translate','verb','academic','communication','번역하다','The app can translate short messages.'),
('L3',12,'treat','verb','general','health','다루다; 치료하다','The clinic can treat minor injuries.'),
('L3',13,'update','verb','workplace','technology','갱신하다; 최신 정보로 바꾸다','Please update the contact details before Friday.'),
('L3',14,'waste','verb','general','environment','낭비하다','Leaving lights on wastes energy.'),
('L3',15,'wonder','verb','general','reasoning','궁금해하다','I wonder why the results changed.'),
('L3',16,'afford','verb','general','money','~할 여유가 있다','Many families cannot afford a larger apartment.'),
('L3',17,'advice','noun','general','people','조언','Her advice helped me choose a course.'),
('L3',18,'detail','noun','academic','communication','세부 사항','The report includes every important detail.'),
('L3',19,'difference','noun','academic','reasoning','차이','We need to explain the difference between the methods.'),
('L3',20,'region','noun','general','geography','지역','The northern region receives more rain.'),
('L3',21,'audience','noun','academic','communication','청중; 관객','The speaker adjusted the talk for a younger audience.'),
('L3',22,'author','noun','academic','literacy','저자','The author cites several local studies.'),
('L3',23,'article','noun','academic','literacy','기사; 논문','I read an article about urban gardens.'),
('L3',24,'device','noun','workplace','technology','장치; 기기','This device records air temperature.'),
('L3',25,'material','noun','workplace','operations','자료; 재료','The builder ordered enough material for the repair.'),
('L3',26,'aspect','noun','academic','reasoning','측면','Cost is one aspect of the decision.'),
('L3',27,'supply','noun','workplace','business','공급; 물량','The store has a limited supply of fresh bread.'),
('L3',28,'income','noun','workplace','employment','수입','Her monthly income changed after the promotion.'),
('L3',29,'budget','noun','workplace','planning','예산','The team prepared a budget for the event.'),
('L3',30,'career','noun','workplace','employment','경력; 직업','He hopes to build a career in design.'),
('L3',31,'contact','noun','workplace','communication','연락처; 접촉','Please contact the office if you need help.'),
('L3',32,'colleague','noun','workplace','employment','동료','A colleague shared a useful report.'),
('L3',33,'employee','noun','workplace','employment','직원','Each employee receives safety training.'),
('L3',34,'employer','noun','workplace','employment','고용주','The employer offers flexible hours.'),
('L3',35,'interview','noun','workplace','employment','면접; 인터뷰','She has an interview on Monday.'),
('L3',36,'course','noun','academic','education','강좌; 과정','This course covers basic research skills.'),
('L3',37,'degree','noun','academic','education','학위','He earned a degree in engineering.'),
('L3',38,'campus','noun','academic','education','캠퍼스','The campus has a new science building.'),
('L3',39,'library','noun','academic','education','도서관','The library stays open during exams.'),
('L3',40,'traffic','noun','general','travel','교통량; 교통','Heavy traffic delayed the bus.'),
('L3',41,'route','noun','general','travel','경로; 노선','This route avoids the busiest roads.'),
('L3',42,'accident','noun','general','travel','사고','The accident blocked one lane.'),
('L3',43,'certain','adjective','academic','reasoning','확실한','I am certain that the figures are correct.'),
('L3',44,'common','adjective','general','description','흔한; 공통의','It is common to feel nervous before an interview.'),
('L3',45,'public','adjective','general','community','공공의; 대중의','The city opened a public reading room.'),
('L3',46,'private','adjective','general','people','사적인; 비공개의','They held a private meeting.'),
('L3',47,'specific','adjective','academic','reasoning','구체적인; 특정한','Please give a specific example.'),
('L3',48,'recent','adjective','academic','time','최근의','The report uses recent data.'),
('L3',49,'abroad','adverb','general','travel','해외에서; 해외로','She studied abroad for one year.'),
('L3',50,'especially','adverb','general','emphasis','특히','I enjoy outdoor activities, especially in spring.'),

('L4',1,'accommodate','verb','workplace','service','수용하다; 편의를 제공하다','The hotel can accommodate another group tonight.'),
('L4',2,'accumulate','verb','academic','research','축적하다; 쌓이다','Small errors can accumulate over time.'),
('L4',3,'confront','verb','general','decisions','맞서다; 직면하다','The committee must confront the cost of the proposal.'),
('L4',4,'convey','verb','academic','communication','전달하다; 나타내다','The chart conveys the main trend clearly.'),
('L4',5,'forecast','verb','academic','research','예측하다','The model can forecast demand for winter services.'),
('L4',6,'enhance','verb','workplace','operations','향상시키다','The update should enhance the security of the system.'),
('L4',7,'launch','verb','workplace','business','출시하다; 시작하다','The company will launch a new training program.'),
('L4',8,'merge','verb','workplace','organization','합병하다; 합쳐지다','The two teams will merge next year.'),
('L4',9,'occupy','verb','general','location','차지하다; 점유하다','The exhibition will occupy the entire east hall.'),
('L4',10,'quote','verb','academic','communication','인용하다','Please quote the source accurately.'),
('L4',11,'recover','verb','general','health','회복하다','Most patients recover within a few days.'),
('L4',12,'recruit','verb','workplace','employment','채용하다; 모집하다','The firm plans to recruit three engineers.'),
('L4',13,'restrict','verb','workplace','policy','제한하다','The rule may restrict access after dark.'),
('L4',14,'secure','verb','workplace','planning','확보하다; 안전하게 하다','We need to secure funding before construction.'),
('L4',15,'shift','verb','workplace','operations','옮기다; 전환하다','The factory will shift production to night hours.'),
('L4',16,'submit','verb','academic','education','제출하다','Students must submit the assignment online.'),
('L4',17,'sustain','verb','general','environment','지속시키다; 지탱하다','The forest cannot sustain heavy traffic.'),
('L4',18,'transmit','verb','workplace','technology','전송하다; 전달하다','The sensor can transmit data to the server.'),
('L4',19,'trigger','verb','general','health','촉발하다; 유발하다','Loud noise can trigger a stress response.'),
('L4',20,'undertake','verb','academic','education','착수하다; 맡다','The class will undertake a short field study.'),
('L4',21,'upgrade','verb','workplace','technology','개선하다; 업그레이드하다','The hospital will upgrade its record system.'),
('L4',22,'validate','verb','academic','research','검증하다; 유효성을 입증하다','The second experiment may validate the original finding.'),
('L4',23,'agency','noun','workplace','governance','기관; 대행사','The agency published new safety guidance.'),
('L4',24,'archive','noun','academic','research','기록 보관소; 문서 자료','The archive contains letters from local residents.'),
('L4',25,'committee','noun','workplace','governance','위원회','The committee reviewed the funding request.'),
('L4',26,'compensation','noun','workplace','employment','보상; 보상금','The contract includes compensation for travel expenses.'),
('L4',27,'conference','noun','academic','communication','회의; 학술 대회','She presented the findings at a regional conference.'),
('L4',28,'database','noun','workplace','technology','데이터베이스','The database stores records securely.'),
('L4',29,'expense','noun','workplace','business','비용; 지출','Travel expense claims are due on Friday.'),
('L4',30,'grant','noun','academic','education','보조금; 연구 지원금','The university awarded a grant for language research.'),
('L4',31,'participant','noun','academic','research','참가자','Each participant completed the same questionnaire.'),
('L4',32,'platform','noun','workplace','technology','플랫폼','The learning platform supports video lessons.'),
('L4',33,'reform','noun','workplace','policy','개혁; 개선','The reform changed how permits are issued.'),
('L4',34,'shortage','noun','general','environment','부족; 품귀','A water shortage affected several villages.'),
('L4',35,'stakeholder','noun','workplace','governance','이해관계자','Each stakeholder received a copy of the plan.'),
('L4',36,'target','noun','workplace','planning','목표; 대상','The team reached its sales target early.'),
('L4',37,'theory','noun','academic','reasoning','이론','The evidence supports the theory.'),
('L4',38,'variable','noun','academic','research','변수','Temperature was the only variable we changed.'),
('L4',39,'volume','noun','workplace','business','양; 부피; 규모','The store reduced the volume of packaging.'),
('L4',40,'workshop','noun','academic','education','워크숍; 실습 모임','The workshop teaches practical writing skills.'),
('L4',41,'global','adjective','general','society','세계적인','The issue has global importance.'),
('L4',42,'gradual','adjective','general','change','점진적인','The gradual recovery surprised the analysts.'),
('L4',43,'neutral','adjective','academic','reasoning','중립적인','The report uses neutral language.'),
('L4',44,'overall','adjective','academic','reasoning','전반적인','The overall result was more positive than expected.'),
('L4',45,'technical','adjective','workplace','technology','기술적인','The manual explains the technical limits.'),
('L4',46,'valid','adjective','academic','reasoning','타당한; 유효한','That is a valid concern about the design.'),
('L4',47,'virtual','adjective','workplace','technology','가상의; 온라인의','The team held a virtual meeting.'),
('L4',48,'meanwhile','adverb','general','time','한편; 그동안','The main road was closed; meanwhile, buses used another route.'),
('L4',49,'unlike','preposition','general','reasoning','~와 달리','Unlike the first trial, the second used volunteers.'),
('L4',50,'within','preposition','workplace','planning','~ 이내에','Please reply within three working days.'),

('L5',1,'alleviate','verb','general','health','완화하다; 고통을 덜다','The new shade trees may alleviate heat in the playground.'),
('L5',2,'calibrate','verb','academic','research','보정하다; 눈금을 맞추다','Technicians calibrate the sensor before each test.'),
('L5',3,'compel','verb','academic','reasoning','강요하다; ~하게 만들다','The evidence may compel us to revise the model.'),
('L5',4,'conceive','verb','academic','production','구상하다; 생각해 내다','The team conceived a device for low-cost testing.'),
('L5',5,'deduce','verb','academic','reasoning','추론하다; 연역하다','We can deduce the missing value from the pattern.'),
('L5',6,'designate','verb','workplace','policy','지정하다','The rules designate one room for confidential meetings.'),
('L5',7,'disrupt','verb','workplace','operations','방해하다; 혼란시키다','A network failure could disrupt the payment system.'),
('L5',8,'elevate','verb','academic','reasoning','높이다; 격상하다','The findings elevate the discussion beyond personal opinion.'),
('L5',9,'embrace','verb','general','change','받아들이다; 포용하다','The community chose to embrace a slower approach to growth.'),
('L5',10,'hinder','verb','academic','education','방해하다','Poor lighting can hinder reading.'),
('L5',11,'initiate','verb','workplace','governance','시작하다; 개시하다','The director will initiate an independent review.'),
('L5',12,'mandate','verb','workplace','policy','명령하다; 의무화하다','The new law mandates regular safety checks.'),
('L5',13,'optimize','verb','workplace','operations','최적화하다','The software is designed to optimize delivery routes.'),
('L5',14,'reject','verb','academic','reasoning','거부하다; 기각하다','Reviewers may reject a claim without sufficient evidence.'),
('L5',15,'refine','verb','academic','production','다듬다; 개선하다','The final round helped refine the survey questions.'),
('L5',16,'resemble','verb','academic','description','닮다; 유사하다','The two patterns resemble each other but are not identical.'),
('L5',17,'stabilize','verb','workplace','business','안정시키다','The policy aims to stabilize prices during the transition.'),
('L5',18,'supplement','verb','academic','education','보완하다; 추가하다','The video supplements the written instructions.'),
('L5',19,'tolerate','verb','general','health','용인하다; 견디다','The material can tolerate high temperatures.'),
('L5',20,'catalyst','noun','general','change','촉매; 계기','The grant became a catalyst for neighborhood renewal.'),
('L5',21,'coherence','noun','academic','communication','일관성; 결속력','The editor checked the coherence of the argument.'),
('L5',22,'compliance','noun','workplace','policy','준수; 순응','The audit measured compliance with safety rules.'),
('L5',23,'controversy','noun','general','society','논란','The proposal caused controversy among local residents.'),
('L5',24,'correlation','noun','academic','research','상관관계','The study found a correlation between sleep and attention.'),
('L5',25,'distribution','noun','workplace','business','분배; 유통','The distribution of supplies took two days.'),
('L5',26,'diversity','noun','general','society','다양성','The festival celebrates the diversity of the region.'),
('L5',27,'domain','noun','academic','education','영역; 분야','This question belongs to the domain of public health.'),
('L5',28,'exception','noun','workplace','policy','예외','The rule has one narrow exception.'),
('L5',29,'exposure','noun','general','health','노출','Long exposure to noise may damage hearing.'),
('L5',30,'frequency','noun','academic','research','빈도','The survey records the frequency of each response.'),
('L5',31,'infrastructure','noun','workplace','operations','기반 시설','The city must repair its transport infrastructure.'),
('L5',32,'integrity','noun','workplace','governance','진실성; 온전성','The system protects the integrity of the records.'),
('L5',33,'literacy','noun','academic','education','문해력; 활용 능력','Digital literacy is essential for this course.'),
('L5',34,'norm','noun','general','society','규범','The study examines how a social norm changes.'),
('L5',35,'scenario','noun','academic','planning','시나리오; 상황 설정','The emergency scenario tested the team plan.'),
('L5',36,'stability','noun','workplace','business','안정성','Investors value stability during uncertain periods.'),
('L5',37,'statistic','noun','academic','research','통계 수치','That statistic should be checked against the original data.'),
('L5',38,'tendency','noun','academic','reasoning','경향','The results show a tendency toward shorter responses.'),
('L5',39,'transition','noun','general','change','전환; 이행','The transition to renewable energy will take time.'),
('L5',40,'vulnerability','noun','workplace','technology','취약성','The update closed a security vulnerability.'),
('L5',41,'ambiguous','adjective','academic','communication','모호한','The sentence is ambiguous without the surrounding context.'),
('L5',42,'beneficial','adjective','general','health','유익한','Regular breaks are beneficial for concentration.'),
('L5',43,'deliberate','adjective','general','decisions','의도적인; 신중한','The change was deliberate, not accidental.'),
('L5',44,'exhaustive','adjective','academic','research','철저한; 빠짐없는','The review is not exhaustive, but it covers the main evidence.'),
('L5',45,'impartial','adjective','workplace','governance','공정한; 치우치지 않은','An impartial chair led the hearing.'),
('L5',46,'inclusive','adjective','general','community','포괄적인','The center follows an inclusive policy for visitors.'),
('L5',47,'rational','adjective','academic','reasoning','합리적인','The report offers a rational explanation for the decline.'),
('L5',48,'credible','adjective','academic','research','신뢰할 수 있는','The source appears credible after independent checks.'),
('L5',49,'mature','adjective','general','nature','성숙한; 다 자란','The trees are mature enough to provide shade.'),
('L5',50,'strategic','adjective','workplace','planning','전략적인','The board made a strategic investment in training.'),

('L6',1,'arbitrate','verb','workplace','governance','중재 판정을 내리다','An independent panel will arbitrate the dispute.'),
('L6',2,'coalesce','verb','general','change','합쳐지다; 하나로 모이다','Several small proposals began to coalesce into one plan.'),
('L6',3,'concede','verb','academic','communication','인정하다; 양보하다','The author concedes that the sample is limited.'),
('L6',4,'discern','verb','academic','research','식별하다; 알아차리다','The analyst could discern a pattern in the responses.'),
('L6',5,'elicit','verb','academic','research','이끌어 내다','The interviewer used open questions to elicit detailed answers.'),
('L6',6,'encompass','verb','academic','reasoning','포괄하다; 아우르다','The framework encompasses social and economic factors.'),
('L6',7,'eradicate','verb','general','health','근절하다','The campaign aims to eradicate the disease from the region.'),
('L6',8,'innovate','verb','workplace','business','혁신하다','Small firms must innovate to remain competitive.'),
('L6',9,'institutionalize','verb','workplace','governance','제도화하다','The reform could institutionalize regular public reporting.'),
('L6',10,'standardize','verb','workplace','operations','표준화하다','The laboratory will standardize its testing procedure.'),
('L6',11,'supersede','verb','workplace','policy','대체하다; 우선하다','The revised guideline will supersede the earlier version.'),
('L6',12,'decouple','verb','academic','reasoning','분리하다; 서로 연결되지 않게 하다','The analysis tries to decouple correlation from causation.'),
('L6',13,'displace','verb','general','society','대체하다; 쫓아내다','Rising rents may displace long-term residents.'),
('L6',14,'entrench','verb','workplace','governance','깊이 뿌리내리게 하다','The arrangement could entrench unequal access to services.'),
('L6',15,'exemplify','verb','academic','communication','예시하다; 전형적으로 보여 주다','The case exemplifies the risks of rushed expansion.'),
('L6',16,'rationalize','verb','workplace','business','합리화하다; 효율적으로 재편하다','The company plans to rationalize its distribution network.'),
('L6',17,'recalibrate','verb','academic','research','재조정하다; 다시 보정하다','Researchers must recalibrate the instrument after the repair.'),
('L6',18,'reconfigure','verb','workplace','technology','재구성하다; 설정을 바꾸다','The engineer will reconfigure the network overnight.'),
('L6',19,'bandwidth','noun','workplace','technology','대역폭; 처리 여유','The video call used most of the available bandwidth.'),
('L6',20,'constituency','noun','workplace','governance','선거구; 이해관계 집단','The representative listened to every constituency in the district.'),
('L6',21,'convergence','noun','academic','research','수렴; 일치','The results show convergence across three independent studies.'),
('L6',22,'discourse','noun','academic','communication','담론; 논의','The paper examines public discourse about migration.'),
('L6',23,'efficacy','noun','academic','health','효능; 효과성','The trial measured the efficacy of the new treatment.'),
('L6',24,'equilibrium','noun','academic','reasoning','균형 상태; 평형','The market moved toward equilibrium after the shortage ended.'),
('L6',25,'fallacy','noun','academic','reasoning','오류; 잘못된 논리','The argument contains a logical fallacy.'),
('L6',26,'feasibility','noun','workplace','planning','실행 가능성','The report assesses the feasibility of the bridge project.'),
('L6',27,'hierarchy','noun','workplace','organization','계층 구조','The diagram shows the hierarchy of the department.'),
('L6',28,'lineage','noun','academic','research','계보; 계통','The database traces the lineage of each sample.'),
('L6',29,'modality','noun','academic','education','방식; 양상','The course offers a digital modality for remote learners.'),
('L6',30,'obstacle','noun','general','decisions','장애물; 방해 요소','Cost remains the main obstacle to wider access.'),
('L6',31,'reciprocity','noun','general','people','상호성; 호혜','The agreement is based on reciprocity between the communities.'),
('L6',32,'redundancy','noun','workplace','operations','중복; 불필요한 반복','The redesign removed redundancy from the data process.'),
('L6',33,'sovereignty','noun','workplace','governance','주권','The treaty recognizes the sovereignty of both states.'),
('L6',34,'subset','noun','academic','research','부분집합; 일부 집단','The analysis used a subset of the full dataset.'),
('L6',35,'synergy','noun','workplace','business','시너지; 상승 효과','The merger created synergy between the two research teams.'),
('L6',36,'analogous','adjective','academic','reasoning','유사한; 비슷한','The two systems are analogous in several important ways.'),
('L6',37,'deterministic','adjective','academic','research','결정론적인; 결과가 정해지는','The model is not deterministic because it includes random variation.'),
('L6',38,'elusive','adjective','academic','reasoning','찾기 힘든; 이해하기 어려운','A single cause remains elusive.'),
('L6',39,'inadvertent','adjective','workplace','communication','무심코 한; 의도하지 않은','The email contained an inadvertent error.'),
('L6',40,'substantive','adjective','academic','communication','실질적인; 중요한','The committee made substantive changes to the proposal.'),
('L6',41,'unprecedented','adjective','general','change','전례 없는','The region experienced unprecedented rainfall this summer.'),
('L6',42,'asymmetrical','adjective','academic','description','비대칭적인','The design has an asymmetrical shape.'),
('L6',43,'concurrently','adverb','workplace','operations','동시에','The two projects were developed concurrently.'),
('L6',44,'meticulously','adverb','academic','research','세심하게; 꼼꼼하게','The samples were labeled meticulously before analysis.'),
('L6',45,'systematically','adverb','academic','research','체계적으로','The team systematically reviewed every response.'),
('L6',46,'conditionally','adverb','workplace','policy','조건부로','The permit was conditionally approved for one year.'),
('L6',47,'tangentially','adverb','academic','reasoning','지엽적으로; 간접적으로','The final paragraph addresses the question only tangentially.'),
('L6',48,'collectively','adverb','general','community','집단적으로','The residents collectively requested safer crossings.'),
('L6',49,'indispensable','adjective','workplace','operations','없어서는 안 될; 필수적인','Accurate records are indispensable to the investigation.'),
('L6',50,'perennial','adjective','general','environment','끊임없는; 매년 되풀이되는','Water access is a perennial concern in the dry region.'),

('L7',1,'circumnavigate','verb','general','travel','주위를 항해하다; 우회하다','The vessel had to circumnavigate the island during the storm.'),
('L7',2,'condescend','verb','general','communication','얕보다; 생색내며 해 주다','The guide did not condescend to the visitors.'),
('L7',3,'contravene','verb','workplace','policy','위반하다; 어긋나다','The decision appears to contravene the agency rules.'),
('L7',4,'deflect','verb','general','communication','방향을 돌리다; 회피하다','The spokesperson tried to deflect criticism with a new proposal.'),
('L7',5,'disavow','verb','academic','communication','부인하다; 관계를 부정하다','The author chose to disavow the earlier statement.'),
('L7',6,'exonerate','verb','workplace','governance','무혐의를 입증하다; 책임을 면하게 하다','New records may exonerate the employee.'),
('L7',7,'expound','verb','academic','communication','상세히 설명하다','The lecturer used examples to expound the central idea.'),
('L7',8,'foreshadow','verb','academic','literacy','미리 암시하다; 예고하다','The opening scene foreshadows the conflict at the end.'),
('L7',9,'forestall','verb','workplace','planning','미연에 방지하다','Early repairs may forestall a more serious failure.'),
('L7',10,'fulminate','verb','general','communication','맹렬히 비난하다','The columnist continued to fulminate against the proposal.'),
('L7',11,'insinuate','verb','academic','communication','넌지시 암시하다','The article seems to insinuate that the results were altered.'),
('L7',12,'inveigh','verb','general','society','맹렬히 공격하다; 비난하다','The speech inveighed against corruption in public offices.'),
('L7',13,'promulgate','verb','workplace','policy','공표하다; 시행하다','The agency will promulgate the revised standard.'),
('L7',14,'recapitulate','verb','academic','communication','요약하여 다시 말하다','The final section recapitulates the main findings.'),
('L7',15,'reconstitute','verb','workplace','organization','재구성하다; 다시 만들다','The board voted to reconstitute the advisory panel.'),
('L7',16,'refute','verb','academic','reasoning','반박하다; 논박하다','The new experiment may refute the original hypothesis.'),
('L7',17,'relinquish','verb','general','decisions','포기하다; 넘겨주다','The founder agreed to relinquish control of the organization.'),
('L7',18,'remonstrate','verb','workplace','governance','항의하다; 따지다','Residents remonstrated with the council about the closure.'),
('L7',19,'instantiate','verb','academic','reasoning','구체적인 예로 보여 주다','The example instantiates the principle in a familiar setting.'),
('L7',20,'denigrate','verb','general','communication','폄하하다; 헐뜯다','The review should criticize the plan without denigrating its creators.'),
('L7',21,'aporia','noun','academic','reasoning','난제; 논리적 막다른 길','The essay ends with an aporia rather than a final answer.'),
('L7',22,'approbation','noun','workplace','governance','찬성; 공식 승인','The plan received formal approbation from the board.'),
('L7',23,'dialectic','noun','academic','reasoning','변증법적 논의','The seminar explored the dialectic between freedom and order.'),
('L7',24,'epistemology','noun','academic','reasoning','인식론','The course introduces the epistemology of scientific inquiry.'),
('L7',25,'exegesis','noun','academic','literacy','주해; 해설','Her exegesis explains the passage in historical context.'),
('L7',26,'imprimatur','noun','workplace','governance','공식 승인; 재가','The proposal cannot proceed without official imprimatur.'),
('L7',27,'jurisprudence','noun','academic','governance','법철학; 판례 체계','The article compares constitutional jurisprudence across countries.'),
('L7',28,'lacuna','noun','academic','research','공백; 빠진 부분','The review identifies a lacuna in the existing evidence.'),
('L7',29,'ontology','noun','academic','technology','존재론; 개념 체계','The database uses an ontology to organize concepts.'),
('L7',30,'panacea','noun','academic','reasoning','만병통치약; 만능 해결책','The policy is useful, but it is not a panacea.'),
('L7',31,'plenitude','noun','general','society','풍부함; 충만','The market offers a plenitude of choices to consumers.'),
('L7',32,'predilection','noun','general','people','선호; 특별한 취향','The survey found a predilection for familiar brands.'),
('L7',33,'schism','noun','general','society','분열; 분파','The dispute created a schism within the association.'),
('L7',34,'teleology','noun','academic','reasoning','목적론','The chapter questions the teleology of economic progress.'),
('L7',35,'vicissitude','noun','general','change','변천; 우여곡절','The memoir follows the vicissitudes of a long career.'),
('L7',36,'antithetical','adjective','academic','reasoning','정반대의; 대조적인','The two explanations are not antithetical; they may work together.'),
('L7',37,'apocryphal','adjective','academic','communication','출처가 의심스러운; 진위가 불확실한','The story is probably apocryphal despite its popularity.'),
('L7',38,'conciliatory','adjective','workplace','communication','화해를 도모하는','The mediator adopted a conciliatory tone.'),
('L7',39,'didactic','adjective','academic','education','교훈적인; 가르치려 드는','The novel is entertaining without becoming overly didactic.'),
('L7',40,'esoteric','adjective','academic','reasoning','난해한; 소수만 아는','The specialist article uses esoteric terminology.'),
('L7',41,'inexorable','adjective','general','change','가차 없는; 막을 수 없는','The inexorable rise in costs forced a redesign.'),
('L7',42,'polemical','adjective','academic','communication','논쟁적인; 공격적인','The essay is forceful but not excessively polemical.'),
('L7',43,'prescient','adjective','general','planning','선견지명이 있는','Her prescient warning helped the team prepare.'),
('L7',44,'protean','adjective','general','change','변화무쌍한; 다재다능한','The artist has a protean style that resists labels.'),
('L7',45,'refractory','adjective','workplace','operations','다루기 힘든; 내화성의','The refractory material retained its shape at high heat.'),
('L7',46,'trenchant','adjective','academic','communication','날카로운; 통렬한','The critic offered a trenchant analysis of the proposal.'),
('L7',47,'unassailable','adjective','academic','reasoning','반박할 수 없는','The conclusion is not unassailable because the sample is small.'),
('L7',48,'peremptorily','adverb','workplace','communication','단호하게; 독단적으로','The request was rejected peremptorily without discussion.'),
('L7',49,'retrospectively','adverb','academic','research','돌이켜 보아','Retrospectively, the early warning seems obvious.'),
('L7',50,'heretofore','adverb','workplace','policy','지금까지; 이전에는','The records had heretofore remained private.')
)
insert into public.vocabulary_catalog(id,content_key,term,meaning,example,part_of_speech,difficulty,cefr_anchor,cefr_band,topics,domains,skills,priority,source,license,provenance)
select ('e3000000-0000-4000-8000-' || lpad(l.ordinal::text,2,'0') || lpad(c.seq::text,10,'0'))::uuid,
  'wl-exp3-' || lower(c.level) || '-' || lpad(c.seq::text,3,'0'),
  c.term,c.meaning,c.example,c.pos,c.level,l.cefr_anchor,l.cefr_band,
  array[c.topic],array[c.domain],
  case c.domain when 'workplace' then array['comprehension','conversation','toeic_listening','toeic_reading']
    when 'academic' then array['literacy','production','comprehension']
    else array['literacy','production','comprehension','conversation'] end,
  70,'WordLoop original editorial content','LicenseRef-WordLoop-Original',
  jsonb_build_object('method','original WordLoop AI-assisted editorial content; no imported course or dictionary text',
    'version','exp3','level_basis','editorial estimate, not certified CEFR classification',
    'review_status','initial editorial pass; not independently calibrated',
    'rights','Original project content; no third-party redistribution license asserted')
from cards c join public.difficulty_levels l on l.code = c.level;

-- Same transparent editorial rules as v1, exp1, and exp2, scoped only to exp3 cards and existing tracks.
with classified as (
  select c.id catalog_id,t.id track_id,
    case
      when t.code = 'det_120_plus' and c.difficulty = 'L5' then 'core'
      when t.code = 'det_120_plus' and c.difficulty = 'L6' then 'stretch'
      when t.code = 'toeic_750' and c.difficulty in ('L3','L4') then 'core'
      when t.code = 'toeic_750' and c.difficulty = 'L5' then 'stretch'
      when t.code = 'toeic_900' and c.difficulty in ('L4','L5') then 'core'
      when t.code = 'toeic_900' and c.difficulty = 'L6' then 'stretch'
      else 'optional' end role,
    case when t.exam = 'DET' then not ('workplace' = any(c.domains))
      else 'workplace' = any(c.domains) end domain_match
  from public.vocabulary_catalog c cross join public.learning_tracks t
  where c.content_key like 'wl-exp3-%' and t.code in ('det_120_plus','toeic_750','toeic_900')
)
insert into public.catalog_track_rules(catalog_id,track_id,role,priority,weight,rationale)
select catalog_id,track_id,role,
  (case role when 'core' then 80 when 'stretch' then 50 else 10 end) + case when domain_match then 10 else 0 end,
  (case role when 'core' then 1.0 when 'stretch' then 0.35 else 0.1 end) * case when domain_match then 1.2 else 1.0 end,
  'Editorial level rule; domain affinity adds priority. Optional means fallback, not automatic promotion.'
from classified;
